### ISSUE TITLE
Example for building UnstructuredGrid from scratch is broken for VTK 8.90.0

### ISSUE THREAD

**Issue by whophil** [pyvista/pyvista#1036]
The example for building UnstructuredGrid from scratch is broken. The traceback complains about inconsistency between the offsets and number of cells.

```
Traceback (most recent call last):
  File "/Users/pchiu/Library/Preferences/PyCharm2019.2/scratches/scratch_195.py", line 69, in <module>
    grid = pv.UnstructuredGrid(offset, cells, celltypes, points)
  File "/Users/pchiu/anaconda3/envs/pv-all/lib/python3.7/site-packages/pyvista/core/pointset.py", line 545, in __init__
    self._check_for_consistency()
  File "/Users/pchiu/anaconda3/envs/pv-all/lib/python3.7/site-packages/pyvista/core/pointset.py", line 672, in _check_for_consistency
    raise ValueError(f'Size of the offset ({self.offset.size}) '
ValueError: Size of the offset (9) must match the number of cells (8)
```

Seems like the issue may be related to the code around https://github.com/pyvista/pyvista/blob/9ddb1b51b3e471e3cbb555d34b8cf966543d0c6e/pyvista/core/pointset.py#L787-L795

For what it's worth, `cattr` has method `GetOffsetsArray` with VTK 8.90.0. 

Some more discussion here: https://pyvista.slack.com/archives/CBA5095UH/p1606587593063500

-----

**To Reproduce**

Snippet lifted from https://docs.pyvista.org/examples/00-load/create-unstructured-surface.html

```py
import numpy as np
import vtk
import pyvista as pv

points = np.array([[0. , 0. , 0. ],
                   [1. , 0. , 0. ],
                   [0.5, 0. , 0. ],
                   [1. , 1. , 0. ],
                   [1. , 0.5, 0. ],
                   [0. , 1. , 0. ],
                   [0.5, 1. , 0. ],
                   [0. , 0.5, 0. ],
                   [0.5, 0.5, 0. ],
                   [1. , 0. , 0.5],
                   [1. , 0. , 1. ],
                   [0. , 0. , 0.5],
                   [0. , 0. , 1. ],
                   [0.5, 0. , 0.5],
                   [0.5, 0. , 1. ],
                   [1. , 1. , 0.5],
                   [1. , 1. , 1. ],
                   [1. , 0.5, 0.5],
                   [1. , 0.5, 1. ],
                   [0. , 1. , 0.5],
                   [0. , 1. , 1. ],
                   [0.5, 1. , 0.5],
                   [0.5, 1. , 1. ],
                   [0. , 0.5, 0.5],
                   [0. , 0.5, 1. ],
                   [0.5, 0.5, 0.5],
                   [0.5, 0.5, 1. ]])


# Each cell in the cell array needs to include the size of the cell
# and the points belonging to the cell.  In this example, there are 8
# hexahedral cells that have common points between them.
cells = np.array([[ 8,  0,  2,  8,  7, 11, 13, 25, 23],
                  [ 8,  2,  1,  4,  8, 13,  9, 17, 25],
                  [ 8,  7,  8,  6,  5, 23, 25, 21, 19],
                  [ 8,  8,  4,  3,  6, 25, 17, 15, 21],
                  [ 8, 11, 13, 25, 23, 12, 14, 26, 24],
                  [ 8, 13,  9, 17, 25, 14, 10, 18, 26],
                  [ 8, 23, 25, 21, 19, 24, 26, 22, 20],
                  [ 8, 25, 17, 15, 21, 26, 18, 16, 22]]).ravel()

# each cell is a VTK_HEXAHEDRON
celltypes = np.empty(8, dtype=np.uint8)
celltypes[:] = vtk.VTK_HEXAHEDRON

# the offset array points to the start of each cell (via flat indexing)
offset = np.array([ 0, 9, 18, 27, 36, 45, 54, 63])

# for example, the 5th cell would be accessed by vtk with:
start_of_cell = offset[4]
n_points_in_cell = cells[start_of_cell]
indices_in_cell = cells[start_of_cell + 1: start_of_cell + n_points_in_cell + 1]
print(indices_in_cell)

# if you are not using VTK 9.0 or newer, you must use the offset array
grid = pv.UnstructuredGrid(offset, cells, celltypes, points)
```

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```txt
  Date: Sat Nov 28 10:34:07 2020 PST

                OS : Darwin
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon Pro 555X OpenGL Engine
       GPU Version : 4.1 ATI-2.11.22

  Python 3.7.9 (default, Aug 31 2020, 07:22:35)  [Clang 10.0.0 ]

           pyvista : 0.27.2
               vtk : 8.90.0
             numpy : 1.19.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.2.0
        matplotlib : 3.3.0
         pyvistaqt : 0.2.0
             PyQt5 : 5.15.1
           IPython : 7.18.1
             scipy : 1.5.2
```

**Comment by adeak** [comment]
On pyvista 0.27.2 and vtk 9.0.1 the code above runs, but I see a warning:
```py
UserWarning: VTK 9 no longer accepts an offset array
  grid = pv.UnstructuredGrid(offset, cells, cell_type, points)
```
This is probably also suboptimal.

**Comment by akaszynski** [comment]
@whophil, you're exactly right, and we should change our VTK 9 check to instead check for anything newer than 8.2.0.  Strangely, VTK doesn't have any official release for 8.90.0 from their official release page at https://vtk.org/download/, so I'm guessing you're using the anaconda package that's also not supported.  See https://discourse.vtk.org/t/where-can-i-get-the-vtk-8-90/3892.

To fix this, we need to modify the version check (and replace `VTK9` with `NEW_VTK` or something like that).

Since this isn't an official build, I'd appreciate help with this check.  If you wouldn't mind submitting a PR, I'll make sure this gets out for the next release.

**Comment by whophil** [comment]
@akaszynski yes, I am using the VTK version which comes with conda-forge ParaView 5.8.1. 

I did som more testing and the current code seems to work fine for VTK 8.2.0 and VTK 9. So it seems like this problem only affects this unsupported/unofficial VTK version. Nevertheless, I opened a #1039 to address this, which does the fix the problem for my specific use case.

**Comment by akaszynski** [comment]
Thanks for adding that.  It's edge cases like these that make using `pyvista` helpful as it will hopefully "just work" for multiple versions of VTK without too much hand tuned code.
