### ISSUE TITLE
UnicodeEncodeError while doing pv.Table(df)

### ISSUE THREAD

**Issue by giovform** [pyvista/pyvista#1162]
**Describe the bug, what's wrong, and what you expect:**

While trying to create a table out of a dataframe (using PVGeo package, which calls PyVista), I get the following error:

`UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 5: ordinal not in range(128)`

The error in question happens when my dataframe contains accents. In this specific case, adding a work like "Anfibólio" causes the error.

-----

**To Reproduce**

```py
import pandas as pd
from PVGeo.interface import data_frame_to_table

lst = ['Anfibólio'] 
df = pd.DataFrame(lst)
tab = vtk.vtkTable()
data_frame_to_table(df, tab)
```

-----

**System Information:**
```txt
--------------------------------------------------------------------------------
  Date: Thu Feb 11 11:00:50 2021 Hora oficial do Brasil
                OS : Windows
            CPU(s) : 16
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.9 GB
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : GeForce GTX 1660/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 456.71
  Python 3.6.7 (default, Dec 13 2020, 23:19:58) [MSC v.1924 64 bit (AMD64)]
           pyvista : 0.28.1
               vtk : 8.2.0
             numpy : 1.19.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.8
        matplotlib : 3.2.1
          colorcet : 1.0.0
             scipy : 1.4.1
              tqdm : 4.50.2
--------------------------------------------------------------------------------
```

**Comment by akaszynski** [comment]
Can you post the traceback of the error?

**Comment by giovform** [comment]
Sure!

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\giovanni\AppData\Local\NA-MIC\Slicer 4.13.0-2020-12-13\lib\Python\Lib\site-packages\PVGeo\interface.py", line 72, in data_frame_to_table
    pdo.DeepCopy(pv.Table(df))
  File "C:\Users\giovanni\AppData\Local\NA-MIC\Slicer 4.13.0-2020-12-13\lib\Python\Lib\site-packages\pyvista\core\objects.py", line 47, in __init__
    self._from_pandas(args[0])
  File "C:\Users\giovanni\AppData\Local\NA-MIC\Slicer 4.13.0-2020-12-13\lib\Python\Lib\site-packages\pyvista\core\objects.py", line 69, in _from_pandas
    self.row_arrays[name] = data_frame[name].values
  File "C:\Users\giovanni\AppData\Local\NA-MIC\Slicer 4.13.0-2020-12-13\lib\Python\Lib\site-packages\pyvista\core\datasetattributes.py", line 63, in __setitem__
    self.append(narray=value, name=key)
  File "C:\Users\giovanni\AppData\Local\NA-MIC\Slicer 4.13.0-2020-12-13\lib\Python\Lib\site-packages\pyvista\core\datasetattributes.py", line 249, in append
    vtk_arr = helpers.convert_array(copy, name, deep=deep_copy)
  File "C:\Users\giovanni\AppData\Local\NA-MIC\Slicer 4.13.0-2020-12-13\lib\Python\Lib\site-packages\pyvista\utilities\helpers.py", line 110, in convert_array
    arr = arr.astype('|S')
UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 5: ordinal not in range(128)
```

**Comment by akaszynski** [comment]
I see the issue.  Looks like we need to encode to UTF-8, and that's handled by `numpy`.  We can get this to work, but it's going to result in ignoring the non-UTF-8 characters:
```
>>> mystr = 'Anfibólio'
>>> np.array(mystr.encode('ascii', 'ignore')).astype('|S')
array(b'Anfiblio', dtype='|S8')
```

It's not perfect, but I can't think of a better solution at this point.  Will that work for you?

**Comment by giovform** [comment]
Hmm, I really need the words as they are.. For now I managed to build the table column by column using a for loops. Thanks!

**Comment by banesullivan** [comment]
Confirmed this still reproduces on current `main` (pyvista 0.48.dev0, vtk 9.6.1) and PVGeo isn't required, it's purely a pyvista issue:

```python
import pandas as pd
import pyvista as pv

pv.Table(pd.DataFrame({'col': ['Anfibólio']}))
# UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 5
```

The failure is in `pyvista/core/utilities/arrays.py` in `convert_array`:

https://github.com/pyvista/pyvista/blob/main/pyvista/core/utilities/arrays.py#L301-L303

```python
if arr.dtype == np.dtype('O'):
    arr = arr.astype('|S')
```

`'|S'` is NumPy's bytestring dtype and defaults to ASCII, so any object-dtype array (which is how pandas stores plain Python strings) containing non-ASCII characters blows up here. The `convert_string_array` branch immediately below already handles `np.str_` (unicode) arrays, so casting object arrays to `'U'` instead of `'|S'` should fix this.
