### ISSUE TITLE
Error creating a slice through (only) hidden cells

### ISSUE THREAD

**Issue by hakostra** [pyvista/pyvista#1179]
**Describe the bug, what's wrong, and what you expect:**

I have a multigrid/multilevel simulation code. The code write out data in Cartesian grids, where 2 cell layers on each side of the grid is "ghost cells". These cells are present in the gird structure for technical reasons, to enforce connectivity between different grids and levels and to introduce boundary conditions in the solution.

These cell layers are also written out in the end and are useful for visualization. I use all of the features described here:
https://blog.kitware.com/ghost-and-blanking-visibility-changes/
The DUPLICATECELL bit is particularly useful for making sure things like contours are contiguous across grid boundaries. In this example this bit is not used, though.

The problem occur when I create a slice through a grid, and the resulting slice ONLY contain HIDDENCELL cell's. The example below reproduce the problem. In this example I create one big grid and embed a smaller grid in the first octant of the parent grid.

Slicing through both grids is not a problem, e.g. slices work in the range x=0..0.5 and x=0.6..1.0, but if the slice hit a region of grid 2 containing ONLY HIDDENCELL's, then it fails with the error below.

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
import pyvista as pv
import vtk
import h5py as h5
import numpy as np

print(pv.Report())

ghostName = vtk.vtkDataSetAttributes.GhostArrayName()
hidden = vtk.vtkDataSetAttributes.HIDDENCELL
dup = vtk.vtkDataSetAttributes.DUPLICATECELL
blocks = pv.MultiBlock()

rng = np.random.default_rng()
size = (14, 14, 14,)

# Grid 1
# 10 cells with dx = 0.1, starting at x=0.0, ending at x=1.0
# + 2 ghost cells, making total grid 14 cells starting from x=-0.2 to x=1.2
# 14 cells -> 15 points
x = np.linspace(-0.2, 1.2, 15)
y = np.linspace(-0.2, 1.2, 15)
z = np.linspace(-0.2, 1.2, 15)
X, Y, Z = np.meshgrid(x, y, z, indexing='ij')
grid1 = pv.StructuredGrid(X, Y, Z)

# Associate some sinteresting data
P = rng.random(size, dtype=np.float32)
grid1.cell_arrays["P"] = P.flatten()

# Set blanking
iblank = np.zeros(size, dtype=np.uint8)

# 2 cells along each side is hidden because they are in the ghost layer
iblank[0:2, :, :] = np.bitwise_or(iblank[0:2, :, :], hidden)
iblank[-2:, :, :] = np.bitwise_or(iblank[-2:, :, :], hidden)
iblank[:, 0:2, :] = np.bitwise_or(iblank[:, 0:2, :], hidden)
iblank[:, -2:, :] = np.bitwise_or(iblank[:, -2:, :], hidden)
iblank[:, :, 0:2] = np.bitwise_or(iblank[:, :, 0:2], hidden)
iblank[:, :, -2:] = np.bitwise_or(iblank[:, :, -2:], hidden)

# Additionally, the lower corner from x = 0..0.5 is refined by another grid
iblank[2:7, 2:7, 2:7] = \
    np.bitwise_or(iblank[2:7, 2:7, 2:7], dup)

grid1.cell_arrays[ghostName] = iblank.flatten()

# Append grid to multigrid collection
blocks.append(grid1)


# Grid 2
# 10 cells with dx = 0.05, starting at x=0.0, ending at x=0.5
# + 2 ghost cells, making total grid 14 cells starting from x=-0.1 to x=0.6
# 14 cells -> 15 points
x = np.linspace(-0.1, 0.6, 15)
y = np.linspace(-0.1, 0.6, 15)
z = np.linspace(-0.1, 0.6, 15)
X, Y, Z = np.meshgrid(x, y, z, indexing='ij')
grid2 = pv.StructuredGrid(X, Y, Z)

# Associate some sinteresting data
P = rng.random(size, dtype=np.float32)
grid2.cell_arrays["P"] = P.flatten()

# Set blanking
iblank = np.zeros(size, dtype=np.uint8)

# 2 cells along each side is hidden because they are in the ghost layer
iblank[0:2, :, :] = np.bitwise_or(iblank[0:2, :, :], hidden)
iblank[-2:, :, :] = np.bitwise_or(iblank[-2:, :, :], hidden)
iblank[:, 0:2, :] = np.bitwise_or(iblank[:, 0:2, :], hidden)
iblank[:, -2:, :] = np.bitwise_or(iblank[:, -2:, :], hidden)
iblank[:, :, 0:2] = np.bitwise_or(iblank[:, :, 0:2], hidden)
iblank[:, :, -2:] = np.bitwise_or(iblank[:, :, -2:], hidden)

grid2.cell_arrays[ghostName] = iblank.flatten()

# Append grid to multigrid collection
blocks.append(grid2)

# A slice through the "hidden" region of grid 2, i.e. in the range x=0.5..0.6 fails
myslice = blocks.slice(origin=[0.55, 0.5, 0.5], normal=[1.0, 0.0, 0.0])
pv.set_plot_theme("document")

plotter = pv.Plotter()
plotter.add_mesh(myslice)
plotter.enable_parallel_projection()
plotter.camera_position = "yz"
plotter.show(screenshot='demo.png')

```
The above fails with the following message:
```
Traceback (most recent call last):
  File "pyvista-ghostbug.py", line 87, in <module>
    plotter.add_mesh(myslice)
  File "/home/hakostra/tmp/vtktest/lib/python3.8/site-packages/pyvista/plotting/plotting.py", line 1538, in add_mesh
    a = self.add_mesh(data, **the_arguments)
  File "/home/hakostra/tmp/vtktest/lib/python3.8/site-packages/pyvista/plotting/plotting.py", line 1727, in add_mesh
    prepare_mapper(scalars)
  File "/home/hakostra/tmp/vtktest/lib/python3.8/site-packages/pyvista/plotting/plotting.py", line 1716, in prepare_mapper
    raise_not_matching(scalars, mesh)
  File "/home/hakostra/tmp/vtktest/lib/python3.8/site-packages/pyvista/utilities/helpers.py", line 695, in raise_not_matching
    raise ValueError(f'Number of scalars ({scalars.size}) ' +
ValueError: Number of scalars (0) must match either the number of points (225) or the number of cells (225).
```

**Screenshots**
This is a "good" screenshot of a slice through x=0.25 to illustrate the structure of the grid:
![demo](https://user-images.githubusercontent.com/3898672/107920156-c78d2800-6f6c-11eb-9277-178c75dd77b3.png)
Notice the refined region in the lower left corner.

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
--------------------------------------------------------------------------------
  Date: Mon Feb 15 09:02:18 2021 CET

                OS : Linux
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : X.Org
      GPU Renderer : Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.0-65-generic, LLVM 11.0.0)
       GPU Version : 4.6 (Core Profile) Mesa 20.2.6

  Python 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]

           pyvista : 0.28.1
               vtk : 9.0.1
             numpy : 1.20.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.8
        matplotlib : 3.3.4
--------------------------------------------------------------------------------

```

**Comment by akaszynski** [comment]
This can work if you disable scalar plotting with:
```py
![demo](https://user-images.githubusercontent.com/11981631/108097744-ca0c8200-703f-11eb-8577-c9259ba559a9.png)

plotter = pv.Plotter()
plotter.add_mesh(myslice, color='w', show_edges=True)
plotter.enable_parallel_projection()
plotter.camera_position = "yz"
plotter.show(screenshot='demo.png')
```

Or if you plot each individual member of the multigrid and check if it's empty or not with a simple `try` ... `except`.  What we need to do is check if the slice is empty before plotting it.
```py
plotter = pv.Plotter()
for item in myslice:
    try:
        plotter.add_mesh(item)
    except:
        pass
plotter.enable_parallel_projection()
plotter.camera_position = "yz"
plotter.show(screenshot='demo.png')
```

![demo](https://user-images.githubusercontent.com/11981631/108100541-481e5800-7043-11eb-9a8d-c3c110d58088.png)

**Comment by hakostra** [comment]
Thanks, the last suggestion is a good workaround.

**Comment by akaszynski** [comment]
Let's keep this issue open and determine if there's a check we can introduce in `pyvista` to look for if a mesh contains only ghost cells/points.

**Comment by hakostra** [comment]
As far as I see it, this issue is solved now. I needed to update my reproducer a bit to make it run with most recent Pyvista, for reference, this is my updated code:

```
import pyvista as pv
import vtk
import h5py as h5
import numpy as np

print(pv.Report())

ghostName = vtk.vtkDataSetAttributes.GhostArrayName()
hidden = vtk.vtkDataSetAttributes.HIDDENCELL
dup = vtk.vtkDataSetAttributes.DUPLICATECELL
blocks = pv.MultiBlock()

rng = np.random.default_rng()
size = (14, 14, 14,)

# Grid 1
# 10 cells with dx = 0.1, starting at x=0.0, ending at x=1.0
# + 2 ghost cells, making total grid 14 cells starting from x=-0.2 to x=1.2
# 14 cells -> 15 points
x = np.linspace(-0.2, 1.2, 15)
y = np.linspace(-0.2, 1.2, 15)
z = np.linspace(-0.2, 1.2, 15)
X, Y, Z = np.meshgrid(x, y, z, indexing='ij')
grid1 = pv.StructuredGrid(X, Y, Z)

# Associate some sinteresting data
P = rng.random(size, dtype=np.float32)
grid1.cell_data["P"] = P.flatten()

# Set blanking
iblank = np.zeros(size, dtype=np.uint8)

# 2 cells along each side is hidden because they are in the ghost layer
iblank[0:2, :, :] = np.bitwise_or(iblank[0:2, :, :], hidden)
iblank[-2:, :, :] = np.bitwise_or(iblank[-2:, :, :], hidden)
iblank[:, 0:2, :] = np.bitwise_or(iblank[:, 0:2, :], hidden)
iblank[:, -2:, :] = np.bitwise_or(iblank[:, -2:, :], hidden)
iblank[:, :, 0:2] = np.bitwise_or(iblank[:, :, 0:2], hidden)
iblank[:, :, -2:] = np.bitwise_or(iblank[:, :, -2:], hidden)

# Additionally, the lower corner from x = 0..0.5 is refined by another grid
iblank[2:7, 2:7, 2:7] = \
    np.bitwise_or(iblank[2:7, 2:7, 2:7], dup)

grid1.cell_data[ghostName] = iblank.flatten()

# Append grid to multigrid collection
blocks.append(grid1)


# Grid 2
# 10 cells with dx = 0.05, starting at x=0.0, ending at x=0.5
# + 2 ghost cells, making total grid 14 cells starting from x=-0.1 to x=0.6
# 14 cells -> 15 points
x = np.linspace(-0.1, 0.6, 15)
y = np.linspace(-0.1, 0.6, 15)
z = np.linspace(-0.1, 0.6, 15)
X, Y, Z = np.meshgrid(x, y, z, indexing='ij')
grid2 = pv.StructuredGrid(X, Y, Z)

# Associate some sinteresting data
P = rng.random(size, dtype=np.float32)
grid2.cell_data["P"] = P.flatten()

# Set blanking
iblank = np.zeros(size, dtype=np.uint8)

# 2 cells along each side is hidden because they are in the ghost layer
iblank[0:2, :, :] = np.bitwise_or(iblank[0:2, :, :], hidden)
iblank[-2:, :, :] = np.bitwise_or(iblank[-2:, :, :], hidden)
iblank[:, 0:2, :] = np.bitwise_or(iblank[:, 0:2, :], hidden)
iblank[:, -2:, :] = np.bitwise_or(iblank[:, -2:, :], hidden)
iblank[:, :, 0:2] = np.bitwise_or(iblank[:, :, 0:2], hidden)
iblank[:, :, -2:] = np.bitwise_or(iblank[:, :, -2:], hidden)

grid2.cell_data[ghostName] = iblank.flatten()

# Append grid to multigrid collection
blocks.append(grid2)

# A slice through the "hidden" region of grid 2, i.e. in the range x=0.5..0.6 fails
myslice = blocks.slice(origin=[0.55, 0.5, 0.5], normal=[1.0, 0.0, 0.0])
pv.set_plot_theme("document")

plotter = pv.Plotter()
plotter.add_mesh(myslice)
plotter.enable_parallel_projection()
plotter.camera_position = "yz"
plotter.show(screenshot='demo.png')
```

Slicing both through x = 0.55 (which originally failed) and x = 0.25 works like a charm and produce the expected results.
