### ISSUE TITLE
Question about using pyinstaller packing with pyvista or vtk

### ISSUE THREAD

**Issue by ycli0536** [pyvista/pyvista#1297]
Hi I'm new in PyVista. I just want to use `pyinstaller` to pack my GUI as an exe using `pyvista`, `pyvistaqt`, and `PyQt5`.
The code I used looks like below (it's just a tabWidget which cannot run directly):
```python
from PyQt5.QtWidgets import QTabWidget
from pyvistaqt import QtInteractor
import pyvista as pv
from UI_init.Ui_tabMesh import Ui_tab_mesh as Ui_TabMesh

class AddTabMesh(QTabWidget, Ui_TabMesh):
    def __init__(self):
        super(AddTabMesh, self).__init__()
        self.setupUi(self)
        self.plotter = QtInteractor(self.groupBox_ViewMesh)
        self.verticalLayout_view.addWidget(self.plotter.interactor)
        self.pushButton_ViewMesh.clicked.connect(self.view_mesh)
    def view_mesh(self):
        # self.get_parameters()
        self.plotter.clear()
        xx, yy, zz = np.meshgrid(self.nodeX, self.nodeY, self.nodeZ)
        grid = pv.StructuredGrid(xx, yy, zz)
        self.plotter.add_mesh(grid, style='wireframe')
        self.plotter.add_bounding_box()
        self.plotter.show_bounds(grid='front', location='outer', all_edges=True)
        self.plotter.add_axes()
```
But I got this information once I use `pyvista` in my GUI after packing and run my exe:
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "GUI\MainWin.py", line 11, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "GUI\TabMesh.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pyvistaqt\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pyvistaqt\plotting.py", line 51, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pyvista\__init__.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pyvista\plotting\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pyvista\plotting\helpers.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pyvista\utilities\__init__.py", line 2, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pyvista\utilities\errors.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pyvista\_vtk.py", line 23, in <module>
ImportError: Failed to load vtkInteractionWidgets: No module named vtkmodules.vtkFiltersGeneral
```
I googled it for a long time but I didn't get relevant solutions. So do you have any idea to fix this problem in packing with pyinstaller?

The packages I used in my environment are:
```
altgraph                  0.17
appdirs                   1.4.4
future                    0.18.2
imageio                   2.9.0
meshio                    4.4.2
numpy                     1.20.2
pefile                    2019.4.18
Pillow                    8.2.0
pip                       21.1.1
pyinstaller               4.3
pyinstaller-hooks-contrib 2021.1
PyQt5                     5.15.4
PyQt5-Qt5                 5.15.2
PyQt5-sip                 12.8.1
PyQt5-stubs               5.15.2.0
pyvista                   0.29.1
pyvistaqt                 0.3.0
pywin32-ctypes            0.2.0
QtPy                      1.9.0
scipy                     1.6.3
scooby                    0.5.7
setuptools                56.0.0
transforms3d              0.3.1
vtk                       9.0.1
```
THANK YOU

**Comment by JBum21** [comment]
Does the code work if you are running it outside of a pyinstaller freeze?

**Comment by JBum21** [comment]
Just kidding... missed saw the last line of your error report. You're going to have to load a VTK hook into your pysintaller. 

Copy and paste this hook into a file named:
hook-vtk.py
```
hiddenimports = ['vtkmodules','vtkmodules.all','vtkmodules.qt.QVTKRenderWindowInteractor',
                 'vtkmodules.util','vtkmodules.util.numpy_support',
                 'vtkmodules.vtkFiltersGeneral']
```
Then, place that file into a folder in your main directly titled "Hooks" or whatever else you please.

Finally, when you are freezing your application using pyinstaller, point to your Hooks directory file by including this line in your terminal command:
`--additional-hooks-dir=./Hooks`

Having this additional hooks directory will be useful in case other libraries have hidden packages.

**Comment by ycli0536** [comment]
> Does the code work if you are running it outside of a pyinstaller freeze?

Yes. It works well
