### ISSUE TITLE
'ERROR:root:No points to subdivide' error while doing boolean difference

### ISSUE THREAD

**Issue by VK1995** [pyvista/pyvista#1517]
I am trying to perform boolean operation on cuboid and my_mesh. 

while generating cuboid I assigned 'my_mesh.center'  to center attribute

```py
path = 'path-to-my_part.stl'

my_mesh = pv.read(path)

def dimensions(mesh):
    bound = mesh.bounds
    l = abs(bound[0]) + abs(bound[1])
    w = abs(bound[2]) + abs(bound[3])
    h = abs(bound[4]) + abs(bound[5])
    return l,w,h

l, b, h = dimensions(my_mesh) 
cuboid = pv.Cube(center=my_mesh.center, x_length=1.4*l, y_length=1.4*b, z_length=1.4*h)

# Triangulated 'my_mesh'
my_mesh_tr = my_mesh.triangulate()

# Triangulated 'cuboid'
cuboid_tr = cuboid.triangulate()

diff = cuboid_tr.boolean_difference(my_mesh_tr)   

diff.save('new_my_part.stl')

```
This returns

![image](https://user-images.githubusercontent.com/84552224/125975534-89ce62f4-c76d-44a9-985d-d6f61757c737.png)

Making some
[my_part.zip](https://github.com/pyvista/pyvista/files/6832073/my_part.zip)
[my_part.zip](https://github.com/pyvista/pyvista/files/6832078/my_part.zip)
[my_part.zip](https://github.com/pyvista/pyvista/files/6832083/my_part.zip)
 adjustments to 'x_length, y_length, z_length' attributes may lead to following error

![image](https://user-images.githubusercontent.com/84552224/125979001-e64226ca-1187-451d-9c6d-2b7e2614d5d7.png)

Please explain why this is happening

I was expecting completion of boolean operation

-----
**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```
```txt
# Paste system info here 
# Didn't get pv.report 
Error: Kernel is dead
at g._sendKernelShellControl (/home/vak/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1013163132/out/client/extension.js:52:854309)
at g.sendShellMessage (/home/vak/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1013163132/out/client/extension.js:52:854078)
at g.requestExecute (/home/vak/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1013163132/out/client/extension.js:52:856620)
at d.requestExecute (/home/vak/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1013163132/out/client/extension.js:37:313414)
at w.requestExecute (/home/vak/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1013163132/out/client/extension.js:24:134487)
at w.executeCodeCell (/home/vak/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1013163132/out/client/extension.js:90:319834)
at w.execute (/home/vak/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1013163132/out/client/extension.js:90:319389)
at w.start (/home/vak/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1013163132/out/client/extension.js:90:315205)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async t.CellExecutionQueue.executeQueuedCells (/home/vak/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1013163132/out/client/extension.js:90:329732)
at async t.CellExecutionQueue.start (/home/vak/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1013163132/out/client/extension.js:90:329272)
```

**Comment by akaszynski** [comment]
Could you try `cuboid = cuboid.clean()`?  I think some of the faces aren't being merged.

**Comment by VK1995** [comment]
@akaszynski Thanks for the reply. 

```cuboid = cuboid.clean() ``` reduces polydata 'N Points' from 24 down to 8. Logical 'my_mesh' get merged inside 'cuboid' on boolean difference. But still having same error.

**Comment by VK1995** [comment]
Hi, am I missing something to add? Please let me know. Thanks!

**Comment by akaszynski** [comment]
> Logically after doing boolean difference, 'my_mesh' should merged inside 'cuboid' and end result should have substracted part geometry from cuboid.

We've refactored the methods and made several notes how the orientation of the normals matter in the upcoming release.  For now, these are in the development documentation at dev.pyvista.org, and we'll have a release out shortly.  This is likely part of the issue you've noted.

**Comment by banesullivan** [comment]
Hi @VK1995, thanks for the detailed report! I revisited this on current `main` (pyvista 0.48.dev, VTK 9.6.1) using the `my_part.stl` you attached, and the original kernel crash / `No points to subdivide` error no longer reproduces. `boolean_difference` now returns cleanly without taking the kernel down.

What's left is a fundamental VTK limitation rather than a pyvista bug: when the cuboid fully encloses the inner mesh (your `1.4 *` dimensions case), the two surfaces don't intersect, so `vtkBooleanOperationPolyDataFilter` has nothing to cut along and returns an empty result. A "solid cuboid with the part hollowed out as an internal void" can't be represented as a single manifold surface anyway. You'd need two separate shells.

Two paths forward depending on what you actually need (or for others who discover this issue in the future)

- If you want the part subtracted from the cuboid as overlapping geometry, size the cuboid so its faces intersect the part rather than fully enclosing it.
- If you want a closed outer cuboid plus an inner cavity matching the part, keep them as two separate `PolyData` (e.g. `pv.MultiBlock([cuboid, my_mesh.flip_normals()])`). That's the manifold-correct representation for a hollow body.

Going to close this one out since the original crash is gone, but please open a new issue if you hit a different boolean failure mode. Thanks again!
