### ISSUE TITLE
Potentially semi-active scalars from pyvista.wrap() causing errors on plotting

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#1693]
I ran into this while implementing https://github.com/pyvista/pyvista/pull/1692:
```py
import pyvista
from vtkmodules.vtkFiltersSources import vtkPlatonicSolidSource

solid = vtkPlatonicSolidSource()
solid.Update()
solid = pyvista.wrap(solid.GetOutput())
solid.plot()
```

This raises:
```
Traceback (most recent call last):
  File "/home/adeak/pyvista/tmp.py", line 7, in <module>
    solid.plot()
  File "/home/adeak/pyvista/pyvista/plotting/helpers.py", line 217, in plot
    plotter.add_mesh(var_item, **kwargs)
  File "/home/adeak/pyvista/pyvista/plotting/plotting.py", line 1942, in add_mesh
    scalars = get_array(mesh, scalars,
  File "/home/adeak/pyvista/pyvista/utilities/helpers.py", line 372, in get_array
    raise KeyError(f'Data array ({name}) not present in this dataset.')
KeyError: 'Data array (None) not present in this dataset.'
```

If I query the active scalars first, the plot works:
```
solid = vtkPlatonicSolidSource()
solid.Update()
solid = pyvista.wrap(solid.GetOutput())
print(solid.cell_data)  # only this is added
solid.plot()  # no error
```

I think the scalars coming out of `wrap()` are in limbo between being active and not. Is this a general issue, or is this specific to `vtkPlatonicSource`?

Once I query the cell scalars, they are called `'Unnamed_0'`:
```
pyvista DataSetAttributes
Association     : CELL
Active Scalars  : Unnamed_0
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays :
    Unnamed_0               int32    (4,)                 SCALARS
```
This is why I opted to rename them in https://github.com/pyvista/pyvista/pull/1692.

**Comment by akaszynski** [comment]
> I think the scalars coming out of wrap() are in limbo between being active and not. Is this a general issue, or is this specific to vtkPlatonicSource?

I have a feeling that this isn't a general issue and we should correct it.

**Comment by zzilch** [comment]
The same thing happens with `vtkMarchingCubes`

**Comment by banesullivan** [comment]
Verified this is fixed on current `main` (0.48.dev0). Both the `vtkPlatonicSolidSource` repro from above and the `vtkMarchingCubes` case now plot without raising. `pv.wrap()` consistently renames anonymous arrays to `Unnamed_<i>` and the active scalar resolves before plotting.

Coverage is mostly there: `test_wrap_auto_names_unnamed_arrays` in `tests/core/test_helpers.py` exercises the rename, and `test_contains_empty_string_preserves_keys_rename_side_effect` in `tests/core/test_datasetattributes.py` covers the `keys()` side-effect path. Closing this out.
