### ISSUE TITLE
Meaningless error message when adding the data values to the point data from unflatten array

### ISSUE THREAD

**Issue by mkondratyev85** [pyvista/pyvista#1761]
**Describe the bug, what's wrong, and what you expect:**

When I try to set point data to a mesh from 3D numpy array (which, I know, is wrong, because I should flatten the array beforehand), I get the error message that, at least to me, has no sense at all.

```python
import numpy as np
import pyvista as pv

data = np.array( [[[4., 3.],
                   [4., 1.],
                   [4., 1.],
                   [4., 1.]],
                 
                  [[4., 4.],
                   [4., 4.],
                   [4., 4.],
                   [4., 4.]],
                 
                  [[4., 4.],
                   [4., 4.],
                   [4., 1.],
                   [4., 1.]],
                 
                  [[4., 4.],
                   [4., 4.],
                   [4., 4.],
                   [4., 1.]]]
                )        

x = np.array([0,500,1000,1500])
y = np.array([0,500,1000,1500])
z = np.array([0,1000])
out = pv.RectilinearGrid(x, y, z)
out['data_values'] = data#.flatten(order='F')
```

And here is the error message:

```
Traceback (most recent call last):
  File "pyvt.py", line 29, in <module>
    out['data_values'] = data#.flattten(order='F')
  File "/home/user/.local/lib/python3.7/site-packages/pyvista/core/dataset.py", line 658, in __setitem__
    raise_not_matching(scalars, self)
  File "/home/user/.local/lib/python3.7/site-packages/pyvista/utilities/helpers.py", line 725, in raise_not_matching
    raise ValueError(f'Number of scalars ({scalars.size}) '
ValueError: Number of scalars (32) must match either the number of points (32) or the number of cells (9).
```

The satirical aspect adds to the fact that the number of scalars (32) does indeed match the number of points(32).

Of course, when I flatten the array - everything works as expected. But when random user sees this error message, it is far from obvious that the cause of the problem is actually the shape of the array, not its size.

Is it possible to make this message more descriptive?

**Comment by adeak** [comment]
This was changed in #3124, we now report `scalars.shape[0]` in the error message. If you find this confusing in some situations still, please let us know.
