### ISSUE TITLE
Active scalars regression

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#1897]
**Describe the bug, what's wrong, and what you expect:**

It's my opinion that the following is a regression

#1593 introduced a regression where a mesh can have arrays but no active scalars

Take a look at my comment: https://github.com/pyvista/pyvista/pull/1881#issuecomment-981981603

-----

**To Reproduce**

```py
>>> from pyvista import examples
>>> points = examples.download_sparse_points()
>>> points
PolyData (0x7fbc79419fa0)
  N Cells:	1
  N Points:	16
  X Bounds:	-1.500e+01, 1.500e+01
  Y Bounds:	5.000e+00, 3.500e+01
  Z Bounds:	2.327e+00, 1.102e+01
  N Arrays:	1

>>> points.threshold()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bane/Software/pyvista/pyvista/pyvista/core/filters/data_set.py", line 842, in threshold
    raise ValueError('No arrays present to threshold.')
ValueError: No arrays present to threshold.
>>>
```

Even though there is 1 array.

-----

**System Information:**
  on main and we're seeing it in the docs

**Comment by banesullivan** [comment]
I can understand the opposite view of this quite well, where you should always be explicit about which scalars to be processing/visualizing but one of the core tenants of PyVista's design is to be simple and easy to use.

From the `CONTRIBUTING.md` guide:

> Make it intuitive. PyVista's goal is to create an intuitive and easy to use interface back to the VTK library. ...

IMO, thresholding (or any filter) a mesh with one array should work without specifying the scalars to use as it intuitively, what other scalars array would I want to threshold on?

**Comment by banesullivan** [comment]
Either way, the error message `ValueError: No arrays present to threshold.` is erroneous and I imagine this is present in many other places

**Comment by adeak** [comment]
We can fix part of this. We now have machinery that can add data arrays both setting them active and not. It seems that (even if we don't implement auto-activation of unambiguous arrays) all the meshes created by _us_ (in this case in `download_sparse_points()`) should have their scalars activated.

And a mostly side note: I wonder if the design choice of always activating one interferes with the concept of active scalars/t_coords/normals/etc. which was also recently added (probably in the same PR, in fact).

**Comment by MatthewFlamm** [comment]
I think we need to be consistent with active attributes, for example, if we set default scalars, we should set also default vectors, normals, etc.  Some filters operate on those.
 What should be the default for each of these?

Can we turn this around and require that all example datasets have active attributes set as necessary?

**Comment by adeak** [comment]
Great minds think alike, @MatthewFlamm :laughing:

**Comment by banesullivan** [comment]
> all the meshes created by us (in this case in download_sparse_points()) should have their scalars activated.

I agree here and think we should ensure this.

Re both of your thoughts on transferring this to tcoords/normals/vectors: I don't think we really want to do that? But I'm mostly indifferent here.

The main thing I think we should address is that meshes created by PyVista should have active scalars (at least) and any PyVista filter that checks for/uses active scalars should auto activate when necessary (e.g. the case with `.filter()` erroring that there are no scalars)

**Comment by MatthewFlamm** [comment]
`.threshold()` only uses scalars while `.streamlines()` only uses vectors.  If we use this logic for `threshold` to motivate setting a default scalars, why not for vectors based on `streamlines` and similar?

Maybe the answer is that this should apply to both scalars or vectors?  I'm not aware of any filters that use the other attributes, but I'm not really sure.  This could backfire later if any exist or get added later.

It also gets tricky if this will also apply to vectors as some 3D data is actually not a vector but a 3 component scalar. How do we distinguish between them to set a default vectors?  I suppose the worst that happens is we plot based on an incorrect type.

**Comment by adeak** [comment]
On a similar note I could imagine that a bunch of defined-on-creation arrays caled `Normals` should neither be active scalars nor vectors. But I don't use these to be sure.

**Comment by akaszynski** [comment]
Personally, I feel that side-effects should be avoided whenever possible, and that we should attempt to mimic VTK's API when it makes sense.

Examples created by us should absolutely have active scalars, because this is the data of interest. However, there are cases in which there is no reason that scalars added to a dataset should be made immediately active. One example is in finite element analysis (FEA) datasets where each point (node) has an additional ID that has no meaning outside of a finite element solver.  In fact, there are many such arrays that have no meaning and will never be visualized; they are merely dataset metadata.

Can we strike a balance where datasets are allowed to have no active point or cell scalars even if they have point or cell data, but are automatically set when using `__setitem__`? We should at the very least ensure that the arrays are active when loaded as examples.

**Comment by adeak** [comment]
> Can we strike a balance where datasets are allowed to have no active point or cell scalars even if they have point or cell data, but are automatically set when using `__setitem__`? 

Isn't this the status quo?

**Comment by akaszynski** [comment]
> Isn't this the status quo?

That's why I want to ensure arrays are active when loaded as examples:

>  We should at the very least ensure that the arrays are active when loaded as examples.

I'm open to suggestions. As pyvista is used for a variety of projects, as wide as finite element analysis and geophysics, it's important to make it applicable for as many projects as possible. I think duplicating VTK's behavior here makes more sense then always enabling a scalar array.

**Comment by adeak** [comment]
I think the status quo (i.e. a dedicated API to specify if data arrays should be activated) plus enforcing that anything we create activates arrays correctly is the good combination. We don't make guesses on behalf of others in unforeseen circumstances, but ensure that our own garden is nice and orderly.

And the API is such that setting arrays as active is a lot more convenient, which agrees with our expectation that _usually_ they should be activated. Whoever doesn't want active arrays can go out of their way to do so. But there's no automatic mechanism to make either choice for the user.

**Comment by banesullivan** [comment]
Pretty sure this has worked itself out
