### ISSUE TITLE
Problems detected in explicit structured grids

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvista#2023]
Explicit structured grid was introduced in the version 0.29.0. In this pull request https://github.com/pyvista/pyvista/pull/1133 there are five examples. The examples 2, 3 and 4 are not producing correct results in the latest version (0.33.0). These examples are working corretly up to the version 0.32.0. See below the expected and presented results.

**2. Show the hidden cells:**

```py
import pyvista as pv

grid = pv.ExplicitStructuredGrid('unisim.vtu')
grid.show_cells()
grid.plot(color='w', show_edges=True, show_bounds=True)
```

Expected:

![image](https://user-images.githubusercontent.com/1608652/149232691-1c7135d4-2f38-42cd-b7cf-f01577024650.png)

Displayed:

![image](https://user-images.githubusercontent.com/1608652/149232724-c8256f6d-3fd5-4f20-b047-0090f612fa2a.png)

**3. Compute the faces connectivity flags array:**

```py
import pyvista as pv

grid = pv.ExplicitStructuredGrid('unisim.vtu')
grid.compute_connectivity()
grid.plot(scalars='ConnectivityFlags', show_edges=True)
```

Expected:

![image](https://user-images.githubusercontent.com/1608652/149233365-da85fa39-a6b3-4fa0-9b07-5f5c0e829cd9.png)

Displayed:

```
Traceback (most recent call last):
  File "D:\Users\Rodrigo\Downloads\examples\example_3.py", line 5, in <module>
    grid.plot(scalars='ConnectivityFlags', show_edges=True)
  File "C:\Python39\lib\site-packages\pyvista\plotting\helpers.py", line 218, in plot
    plotter.add_mesh(var_item, **kwargs)
  File "C:\Python39\lib\site-packages\pyvista\plotting\plotting.py", line 2064, in add_mesh
    scalars = get_array(mesh, scalars,
  File "C:\Python39\lib\site-packages\pyvista\utilities\helpers.py", line 374, in get_array
    raise KeyError(f'Data array ({name}) not present in this dataset.')
KeyError: 'Data array (ConnectivityFlags) not present in this dataset.'
```

**4. Compute an array with the number of connected cell faces:**

```py
import pyvista as pv

grid = pv.ExplicitStructuredGrid('unisim.vtu')
grid.compute_connections()
grid.plot(scalars='number_of_connections', show_edges=True)
```

Expected:

![image](https://user-images.githubusercontent.com/1608652/149233463-2c33f4af-84aa-4173-b682-8e9fce95ec1d.png)

Displayed:

```
Traceback (most recent call last):
  File "D:\Users\Rodrigo\Downloads\examples\example_4.py", line 5, in <module>
    grid.plot(scalars='number_of_connections', show_edges=True)
  File "C:\Python39\lib\site-packages\pyvista\plotting\helpers.py", line 218, in plot
    plotter.add_mesh(var_item, **kwargs)
  File "C:\Python39\lib\site-packages\pyvista\plotting\plotting.py", line 2064, in add_mesh
    scalars = get_array(mesh, scalars,
  File "C:\Python39\lib\site-packages\pyvista\utilities\helpers.py", line 374, in get_array
    raise KeyError(f'Data array ({name}) not present in this dataset.')
KeyError: 'Data array (number_of_connections) not present in this dataset.'
```

**Comment by rodrigomologni** [comment]
Hi @banesullivan! I identified that these problems started from your pull request #1860. I think you will be able to identify the origin of the problems faster than I can.

**Comment by rodrigomologni** [comment]
Solutions for the problems 3 and 4:

```py
grid = grid.compute_connectivity()
grid = grid.compute_connections()
```

**Comment by rodrigomologni** [comment]
I was out of date with the updates on pyvista. The problems reported by me are not real problems. Sorry for the my mistake.
