### ISSUE TITLE
Theme validation on import requires matplotlib

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#2144]
Matplotlib has always been a soft dependency of PyVista. Recent releases have broken on import if installing PyVista in a fresh environment without matplotlib:

```
$ pip install --no-cache  --find-links https://wheels.pyvista.org pyvista
Looking in links: https://wheels.pyvista.org
Collecting pyvista
  Downloading pyvista-0.33.2-py3-none-any.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 24.1 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.22.2-cp310-cp310-macosx_10_14_x86_64.whl (17.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 78.9 MB/s eta 0:00:00
Collecting pillow
  Downloading Pillow-9.0.1-cp310-cp310-macosx_10_10_universal2.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 66.0 MB/s eta 0:00:00
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting scooby>=0.5.1
  Downloading scooby-0.5.11-py3-none-any.whl (14 kB)
Collecting vtk
  Downloading https://wheels.pyvista.org/vtk-9.1.0.dev0-cp310-cp310-macosx_12_0_x86_64.whl (38.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.0/38.0 MB 78.7 MB/s eta 0:00:00
Collecting imageio
  Downloading imageio-2.14.1-py3-none-any.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 69.4 MB/s eta 0:00:00
Installing collected packages: vtk, scooby, appdirs, pillow, numpy, imageio, pyvista
Successfully installed appdirs-1.4.4 imageio-2.14.1 numpy-1.22.2 pillow-9.0.1 pyvista-0.33.2 scooby-0.5.11 vtk-9.1.0.dev0
```

```py
Python 3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:32:15) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
No jedi here. Coming to the dark side.
>>> import pyvista
Traceback (most recent call last):
  File "/Users/bane/Software/pyvista/pyvista/pyvista/plotting/colors.py", line 400, in get_cmap_safe
    from matplotlib.cm import get_cmap
ModuleNotFoundError: No module named 'matplotlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bane/Software/pyvista/pyvista/pyvista/__init__.py", line 31, in <module>
    set_plot_theme(os.environ['PYVISTA_PLOT_THEME'].lower())
  File "/Users/bane/Software/pyvista/pyvista/pyvista/themes.py", line 125, in set_plot_theme
    pyvista.global_theme.load_theme(new_theme_type())
  File "/Users/bane/Software/pyvista/pyvista/pyvista/themes.py", line 2304, in __init__
    self.cmap = 'viridis'
  File "/Users/bane/Software/pyvista/pyvista/pyvista/themes.py", line 1561, in cmap
    get_cmap_safe(cmap)  # for validation
  File "/Users/bane/Software/pyvista/pyvista/pyvista/plotting/colors.py", line 402, in get_cmap_safe
    raise ImportError('cmap requires matplotlib')
ImportError: cmap requires matplotlib
>>> exit()
(vtkbuild310) ➜  pyvista git:(maint/pyvista-wheels) python
Python 3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:32:15) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
No jedi here. Coming to the dark side.
>>>
```

**Comment by adeak** [comment]
FYI VTK depends on matplotlib now, see https://github.com/pyvista/pyvista/pull/2828#issuecomment-1160739080. This might mean that this is a very recent change.

**Comment by adeak** [comment]
Yeah, good shout. We still do, see e.g. https://github.com/pyvista/pyvista/pull/2824 https://github.com/pyvista/pyvista/pull/2823 https://github.com/pyvista/pyvista/pull/2828.
