### ISSUE TITLE
None of the UniformGrid-specific filters work on `cell_data` arrays.

### ISSUE THREAD

**Issue by njneeteson** [pyvista/pyvista#2217]
None of the `image_*` UniformGrid filter methods work when `cell_data` is set as the active / preferred scalars. I discovered this while trying to wrap vtkUniformConstantPad and not being able to get the `cell_data` in the `example.load_uniform()` example `UniformGrid` to come through to the output. I then went back and tested `gaussian_smooth` and `median_smooth` and it's the same thing.

I'm a little bit out of my depth here and I could use some input on what the issue could be.

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
import numpy as np
import pyvista

cell_data = np.ones((9, 9, 9))
cell_data[4, 4, 4] = 100
volume = pyvista.UniformGrid(dims=(10, 10, 10))
volume.cell_data['cell_data'] = cell_data.flatten(order='F')

print(volume.active_scalars_info)

volume_smoothed = volume.gaussian_smooth()
```

Output:
```
python check_gaussian.py
ActiveArrayInfo(association=<FieldAssociation.CELL: 1>, name='cell_data')
2022-02-14 16:36:18.006 (   0.215s) [          C666AC]       vtkImageData.cxx:1385   ERR| vtkImageData (0x7fde579361d0): No Scalar Field has been specified - assuming 1 component!
2022-02-14 16:36:18.006 (   0.215s) [          C666BC]       vtkImageData.cxx:1385   ERR| vtkImageData (0x7fde579361d0): No Scalar Field has been specified - assuming 1 component!
2022-02-14 16:36:18.006 (   0.215s) [          C666B8]       vtkImageData.cxx:1385   ERR| vtkImageData (0x7fde579361d0): No Scalar Field has been specified - assuming 1 component!
2022-02-14 16:36:18.006 (   0.215s) [          C666B9]       vtkImageData.cxx:1385   ERR| vtkImageData (0x7fde579361d0): No Scalar Field has been specified - assuming 1 component!
2022-02-14 16:36:18.006 (   0.215s) [          C666BD]       vtkImageData.cxx:1385   ERR| vtkImageData (0x7fde579361d0): No Scalar Field has been specified - assuming 1 component!
2022-02-14 16:36:18.006 (   0.215s) [          C666BE]       vtkImageData.cxx:1385   ERR| vtkImageData (0x7fde579361d0): No Scalar Field has been specified - assuming 1 component!
2022-02-14 16:36:18.006 (   0.215s) [          C666BB]       vtkImageData.cxx:1385   ERR| vtkImageData (0x7fde579361d0): No Scalar Field has been specified - assuming 1 component!
2022-02-14 16:36:18.006 (   0.215s) [          C666BA]       vtkImageData.cxx:1385   ERR| vtkImageData (0x7fde579361d0): No Scalar Field has been specified - assuming 1 component!
ERROR:root:No Scalar Field has been specified - assuming 1 component!
zsh: segmentation fault  python check_gaussian.py
```
-----

Here's my implementation of `image_pad` and some sample output below after applying it to the example `UniformGrid`. The end of the method gets a bit gross because I was trying different things to see if the `alg` would process the `cell_data` but to no avail. (indentation also got a bit messed up copy-pasting)

```py
def image_pad(
        self,
        pad_size,
        mode = 'constant',
        constant_value = 0,
        progress_bar = False
    ):
        """Pad a uniform grid. Can also be used to crop if negative ``'pad_size'`` values are given.

        Modes:
        Constant - Makes image larger by padding with constant.
        Mirror - Extra pixels are filled by mirror images.
        Wrap - Makes an image larger by wrapping existing data.

        Parameters
        ----------
        pad_size : int or list(int) or tuple(int)
            How many voxels to pad the image with. If a single int is given, pad
            all sides of the image with this amount. If a length 3 iterable is
            given as ``(x_pad,y_pad,z_pad)``, pad both sides of each dimension by
            the given amount. If a length 6 iterable is given as
            ``(x_low_padd,x_upp_pad,y_low_padd,y_upp_pad,z_low_padd,z_upp_pad)``,
            the edges of the image will be padded accordingly.

        mode : string, optional
            Can be ``'constant'``, ``'mirror'``, or ``'wrap'``.
            Constant: extra padded voxels assigned values as ``'constant_value'``.
            Mirror: extra padded voxels are assigned values by reflecting from the edge.
            Wrap: extra padded voxels are assigned values from the opposite edge.
            Default ``'constant'``.

        constant_value : float or int, optional
            The constant value to assign to extra voxels when mode is ``'constant'``.
            Default is 0.

        progress_bar : bool, optional
            Display a progress bar to indicate progress. Default ``False``.

        Returns
        -------
        pyvista.UniformGrid
            Dataset with extra padded voxels.


        """
        if mode is 'constant':
            alg = _vtk.vtkImageConstantPad()
            alg.SetConstant(constant_value)
        elif mode is 'mirror':
            alg = _vtk.vtkImageMirrorPad()
        elif mode is 'wrap':
            alg = _vtk.vtkImageWrapPad()
        else:
            raise ValueError('mode must be constant, mirror, or wrap.')
        alg.SetInputDataObject(self)
        _update_alg(alg)  # need to update midway to be able to get the extents
        current_extents = np.asarray(alg.GetOutputWholeExtent())
        if isinstance(pad_size, int):
            shift_extents = np.array([-pad_size, pad_size, -pad_size, pad_size, -pad_size, pad_size])
        elif isinstance(pad_size, collections.abc.Iterable):
            if len(pad_size) == 3:
                shift_extents = np.array([-pad_size[0], pad_size[0], -pad_size[1], pad_size[1], -pad_size[2], pad_size[2]])
            elif len(pad_size) == 6:
                shift_extents = np.array(pad_size)
                # use a list comprehension to make the even values negative
                shift_extents = np.array([val if idx%2 else -val for idx, val in enumerate(shift_extents)])
            else:
                raise ValueError('pad_size must be length 3 or 6, if iterable.')
        else:
            raise TypeError('pad_size must be int or iterable.')
        padded_extents = current_extents + shift_extents
        alg.SetOutputWholeExtent(padded_extents)
        _update_alg(alg, progress_bar, 'Padding Image - adding voxels')
        output = _get_output(alg)
        # need to process all of the cell and point arrays, not just a particular one
        for scalars in self.cell_data.keys():
            field = self.get_array_association(scalars, preference='cell')
            alg.SetInputArrayToProcess(0,0,0,field.value,scalars)
            _update_alg(alg, progress_bar, f'Padding Image - cell data - {scalars}')
            output.cell_data[scalars] = _get_output(alg).cell_data[scalars]
        for scalars in self.point_data.keys():
            field = self.get_array_association(scalars, preference='point')
            alg.SetInputArrayToProcess(0,0,0,field.value,scalars)
            _update_alg(alg, progress_bar, f'Padding Image - point data - {scalars}')
            output.point_data[scalars] = _get_output(alg).point_data[scalars]
        return output
```

So what's happening here is when it goes to pad the `cell_data` the Dataset I want to stick it in expects a an array of shape (1331,) - that's 11^3. However when the alg is supposed to process the `cell_data` it just does not and produces an array of size (0,).
```
python check_pad.py     
Padding Image - adding voxels: 100%|███████████████████████████████████████████[00:00<00:00]
Padding Image - cell data - Spatial Cell Data: 100%|███████████████████████████[00:00<00:00]
Traceback (most recent call last):
  File "check_pad.py", line 12, in <module>
    padded = grid.image_pad(1, progress_bar=True)
  File "/Users/nathanneeteson/Projects/active_development/pyvista/pyvista/core/filters/uniform_grid.py", line 348, in image_pad
    output.cell_data[scalars] = _get_output(alg).cell_data[scalars]
  File "/Users/nathanneeteson/Projects/active_development/pyvista/pyvista/core/datasetattributes.py", line 227, in __setitem__
    self.set_array(value, name=key)
  File "/Users/nathanneeteson/Projects/active_development/pyvista/pyvista/core/datasetattributes.py", line 613, in set_array
    vtk_arr = self._prepare_array(data, name, deep_copy)
  File "/Users/nathanneeteson/Projects/active_development/pyvista/pyvista/core/datasetattributes.py", line 769, in _prepare_array
    raise ValueError(f'data length of ({data.shape[0]}) != required length ({array_len})')
ValueError: data length of (0) != required length (1331)
```

This is some output from a prior iteration of the method where I naively assumed if I did not specify anything using `SetInputArrayToProcess` that it would just pad all of the scalar arrays appropriately.
```
original image
pyvista DataSetAttributes
Association     : POINT
Active Scalars  : Spatial Point Data
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays :
    Spatial Point Data      float64  (1000,)              SCALARS
pyvista DataSetAttributes
Association     : CELL
Active Scalars  : None
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays :
    Spatial Cell Data       float64  (729,)

padded image
pyvista DataSetAttributes
Association     : POINT
Active Scalars  : Spatial Cell Data
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays :
    Spatial Cell Data       float64  (1728,)              SCALARS
pyvista DataSetAttributes
Association     : CELL
Active Scalars  : None
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays :
    Spatial Cell Data       float64  (0,)

```

-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
# Paste system info here
--------------------------------------------------------------------------------
  Date: Mon Feb 14 16:37:10 2022 MST

                OS : Darwin
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 16.0 GiB
       Environment : Python
       File system : apfs
        GPU Vendor : Intel Inc.
      GPU Renderer : Intel(R) Iris(TM) Plus Graphics OpenGL Engine
       GPU Version : 4.1 INTEL-18.3.5

  Python 3.7.11 (default, Jul 27 2021, 07:03:16)  [Clang 10.0.0 ]

           pyvista : 0.34.dev0
               vtk : 9.1.0
             numpy : 1.21.5
           imageio : 2.14.1
           appdirs : 1.4.4
            scooby : 0.5.11
        matplotlib : 3.5.1
           IPython : 7.31.1
          colorcet : 3.0.0
           cmocean : 2.0
        ipyvtklink : 0.2.2
             scipy : 1.7.3
        itkwidgets : 0.32.1
              tqdm : 4.62.3
            meshio : 5.3.0
--------------------------------------------------------------------------------
```

**Comment by adeak** [comment]
Just a quick comment that it's perfectly plausible that only point data are supported in VTK, see e.g. examples for the same in https://github.com/pyvista/pyvista/issues/2037.

**Comment by njneeteson** [comment]
> Just a quick comment that it's perfectly plausible that only point data are supported in VTK, see e.g. examples for the same in #2037 for some other filters.

If this is the case, I will open up a separate PR to update all of the affected UniformGrid filters to:

- note in the doc string that only point data is supported
- warn users that even if they just operate on point data, all cell data will be lost in the output
- recommend users convert their cell data to point data if they want to use the filters
- update the parameters (no need for "preference" if you can't process cell data)
- check the active scalars and/or scalars input parameter value and raise an Exception if the user is trying to operate on cell data

I'll leave this for maybe a week or so and see if anyone else chimes in and go ahead with the above if no-one has other ideas.

**Comment by njneeteson** [comment]
Alright I left this longer than I intended to (work got busy) but I will follow through on the above plan in the near future. We will abandon support for cell data in image filters under the assumption that VTK doesn't support it in those filters. I can try to add in a workaround to not destroy all of the cell (and field?) data and we can adjudicate whether my solution is too kludgy (or whether cell data should just be destroyed) at the PR stage.
