### ISSUE TITLE
[Bug?] Non-standard locale causes issues for ASCII encoding

### ISSUE THREAD

**Issue by supersubscript** [pyvista/pyvista#226]
I have issues running the pyvista tests locally, as there seems to be an issue with loading files in certain formats. I'm running the following platform (generated with mne):

```python
Platform:      Linux-4.15.0-50-generic-x86_64-with-debian-buster-sid
Python:        3.7.2 (default, Dec 29 2018, 06:19:36)  [GCC 7.3.0]
Executable:    /home/henrik/.local/anaconda2/envs/surface/bin/python
CPU:           x86_64: 4 cores
Memory:        7.7 GB

mne:           0.18.0
numpy:         1.16.1 {blas=openblas, lapack=openblas}
scipy:         1.2.1
matplotlib:    3.0.2 {backend=Qt5Agg}

sklearn:       Not found
nibabel:       Not found
mayavi:        Not found
cupy:          Not found
pandas:        0.24.1
dipy:          Not found
``` 

Running `python -m pytest -v --cov pyvista` gives the following error (to do with saving files in ascii format; looks like some nan values are messing things up):
```python
========================================== FAILURES ==========================================
____________________________________ test_save[vtk-False] ____________________________________

extension = 'vtk', binary = False
tmpdir = local('/tmp/pytest-of-henrik/pytest-5/test_save_vtk_False_1')

    @pytest.mark.parametrize('binary', [True, False])
    @pytest.mark.parametrize('extension', ['stl', 'vtk', 'ply', 'vtp'])
    def test_save(extension, binary, tmpdir):
        sphere = SPHERE.copy()
        filename = str(tmpdir.mkdir("tmpdir").join('tmp.%s' % extension))
        sphere.save(filename, binary)
    
        mesh = pyvista.PolyData(filename)
>       assert mesh.faces.shape == sphere.faces.shape
E       assert (0,) == (640,)
E         At index 0 diff: 0 != 640
E         Full diff:
E         - (0,)
E         + (640,)
E         ?  ++
tests/test_polydata.py:260: AssertionError
``` 

Also when trying to generate the docs locally, I get similar loading errors:
```python
make doctest
``` 
```python
Running Sphinx v1.8.4
Adding copy buttons to code blocks...
making output directory...
generating gallery...
WARNING: /home/henrik/projects/pyvista/examples/00-load/read-file.py failed to execute correctly: Traceback (most recent call last):
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 394, in _memory_usage
    out = func()
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 382, in __call__
    exec(self.code, self.globals)
  File "/home/henrik/projects/pyvista/examples/00-load/read-file.py", line 74, in <module>
    mesh = examples.download_doorman()
  File "/home/henrik/projects/vtki/pyvista/examples/downloads.py", line 241, in download_doorman
    return _download_and_read('doorman/doorman.obj')
  File "/home/henrik/projects/vtki/pyvista/examples/downloads.py", line 58, in _download_and_read
    return pyvista.read(saved_file)
  File "/home/henrik/projects/vtki/pyvista/readers.py", line 166, in read
    return pyvista.PolyData(filename)
  File "/home/henrik/projects/vtki/pyvista/pointset.py", line 76, in __init__
    self._load_file(args[0])
  File "/home/henrik/projects/vtki/pyvista/pointset.py", line 151, in _load_file
    if not np.any(self.points):
  File "/home/henrik/projects/vtki/pyvista/common.py", line 125, in points
    vtk_data = self.GetPoints().GetData()
AttributeError: 'NoneType' object has no attribute 'GetData'

generating gallery for examples/00-load... [100%] read-parallel.py                            
WARNING: /home/henrik/projects/pyvista/examples/01-filter/extract-edges.py failed to execute correctly: Traceback (most recent call last):
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 394, in _memory_usage
    out = func()
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 382, in __call__
    exec(self.code, self.globals)
  File "/home/henrik/projects/pyvista/examples/01-filter/extract-edges.py", line 25, in <module>
    mesh = examples.download_nefertiti()
  File "/home/henrik/projects/vtki/pyvista/examples/downloads.py", line 136, in download_nefertiti
    return _download_and_read('Nefertiti.obj.zip')
  File "/home/henrik/projects/vtki/pyvista/examples/downloads.py", line 58, in _download_and_read
    return pyvista.read(saved_file)
  File "/home/henrik/projects/vtki/pyvista/readers.py", line 166, in read
    return pyvista.PolyData(filename)
  File "/home/henrik/projects/vtki/pyvista/pointset.py", line 76, in __init__
    self._load_file(args[0])
  File "/home/henrik/projects/vtki/pyvista/pointset.py", line 151, in _load_file
    if not np.any(self.points):
  File "/home/henrik/projects/vtki/pyvista/common.py", line 125, in points
    vtk_data = self.GetPoints().GetData()
AttributeError: 'NoneType' object has no attribute 'GetData'

WARNING: /home/henrik/projects/pyvista/examples/01-filter/resample.py failed to execute correctly: Traceback (most recent call last):
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 394, in _memory_usage
    out = func()
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 382, in __call__
    exec(self.code, self.globals)
  File "/home/henrik/projects/pyvista/examples/01-filter/resample.py", line 45, in <module>
    surface = examples.download_saddle_surface()
  File "/home/henrik/projects/vtki/pyvista/examples/downloads.py", line 153, in download_saddle_surface
    return _download_and_read('InterpolatingOnSTL_final.stl')
  File "/home/henrik/projects/vtki/pyvista/examples/downloads.py", line 58, in _download_and_read
    return pyvista.read(saved_file)
  File "/home/henrik/projects/vtki/pyvista/readers.py", line 166, in read
    return pyvista.PolyData(filename)
  File "/home/henrik/projects/vtki/pyvista/pointset.py", line 76, in __init__
    self._load_file(args[0])
  File "/home/henrik/projects/vtki/pyvista/pointset.py", line 151, in _load_file
    if not np.any(self.points):
  File "/home/henrik/projects/vtki/pyvista/common.py", line 125, in points
    vtk_data = self.GetPoints().GetData()
AttributeError: 'NoneType' object has no attribute 'GetData'

generating gallery for examples/01-filter... [100%] volume-smoothing.py                       
Fatal Python error: Segmentation faultt... [ 14%] plot-cmap.py                                

Current thread 0x00007f2373f9f740 (most recent call first):
  File "/home/henrik/projects/vtki/pyvista/readers.py", line 118 in standard_reader_routine
  File "/home/henrik/projects/vtki/pyvista/readers.py", line 180 in read
  File "/home/henrik/projects/vtki/pyvista/examples/downloads.py", line 58 in _download_and_read
  File "/home/henrik/projects/vtki/pyvista/examples/downloads.py", line 79 in download_st_helens
  File "/home/henrik/projects/pyvista/examples/02-plot/plot-cmap.py", line 23 in <module>
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 382 in __call__
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 394 in _memory_usage
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 447 in execute_code_block
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 565 in <listcomp>
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 565 in execute_script
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 634 in generate_file_rst
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 317 in generate_dir_rst
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py", line 287 in generate_gallery_rst
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx/events.py", line 80 in emit
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx/application.py", line 510 in emit
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx/application.py", line 325 in _init_builder
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx/application.py", line 263 in __init__
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303 in build_main
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx/cmd/make_mode.py", line 162 in run_generic_build
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx/cmd/make_mode.py", line 175 in run_make_mode
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx/cmd/build.py", line 206 in make_main
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx/cmd/build.py", line 317 in main
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/site-packages/sphinx/__main__.py", line 16 in <module>
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/runpy.py", line 85 in _run_code
  File "/home/henrik/.local/anaconda2/envs/surface/lib/python3.7/runpy.py", line 193 in _run_module_as_main
Segmentation fault (core dumped)
Makefile:20: recipe for target 'doctest' failed
make: *** [doctest] Error 139
```

**Comment by GuillaumeFavelier** [comment]
I can't reproduce on my configuration (generated by mne):
```sh
Platform:      Linux-4.19.42-1-MANJARO-x86_64-with-arch-Manjaro-Linux
Python:        3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)  [GCC 7.3.0]
Executable:    /home/guillaume/source/anaconda3/envs/mne-vtki/bin/python
CPU:           : 4 cores
Memory:        7.7 GB

mne:           0.19.dev0
numpy:         1.16.2 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.2.1
matplotlib:    3.0.3 {backend=Qt5Agg}

sklearn:       0.20.3
nibabel:       2.4.0
mayavi:        4.6.2 {qt_api=pyqt5, PyQt5=5.11.3}
cupy:          Not found
pandas:        0.24.2
dipy:          Not found
```

What happens if you try the following in the same environment?
```py
import vtk

sphere = vtk.vtkSphereSource()
sphere.Update()

writer = vtk.vtkPolyDataWriter()
writer.SetFileName("test.vtk")
writer.SetInputData(sphere.GetOutput())
writer.SetFileTypeToASCII()
writer.Write()
```
This script creates a ASCII file called `test.vtk`.

**Comment by supersubscript** [comment]
Executing your snippet gives:
```python
ERROR:root:,5
50
```

Also:
```python
pyvista.wrap(sphere.GetOutput())
Out[54]: 
PolyData (0x7f77bcfa3768)
  N Cells:	96
  N Points:	50
  X Bounds:	-4.875e-01, 4.875e-01
  Y Bounds:	-4.875e-01, 4.875e-01
  Z Bounds:	-5.000e-01, 5.000e-01
  N Scalars:	1

pyvista.PolyData('test.vtk')
ERROR:root:,5
Out[55]: 
PolyData (0x7f77bcfa3a08)
  N Cells:	0
  N Points:	50
  X Bounds:	-3.109e-02, 4.842e+30
  Y Bounds:	-5.181e+04, 6.380e+28
  Z Bounds:	-5.181e+04, 7.923e+34
  N Scalars:	0
```

**Comment by supersubscript** [comment]
Here's my output file:
```
# vtk DataFile Version 4.2
vtk output
ASCII
DATASET POLYDATA
POINTS 50 float
0 0 0,5 0 0 -0,5 0,216942 0 0,450484 
0,390916 0 0,311745 0,487464 0 0,11126 0,487464 0 -0,11126 
0,390916 0 -0,311745 0,216942 0 -0,450484 0,153401 0,153401 0,450484 
0,276419 0,276419 0,311745 0,344689 0,344689 0,11126 0,344689 0,344689 -0,11126 
0,276419 0,276419 -0,311745 0,153401 0,153401 -0,450484 1,32839e-17 0,216942 0,450484 
2,39367e-17 0,390916 0,311745 2,98486e-17 0,487464 0,11126 2,98486e-17 0,487464 -0,11126 
2,39367e-17 0,390916 -0,311745 1,32839e-17 0,216942 -0,450484 -0,153401 0,153401 0,450484 
-0,276419 0,276419 0,311745 -0,344689 0,344689 0,11126 -0,344689 0,344689 -0,11126 
-0,276419 0,276419 -0,311745 -0,153401 0,153401 -0,450484 -0,216942 2,65677e-17 0,450484 
-0,390916 4,78734e-17 0,311745 -0,487464 5,96971e-17 0,11126 -0,487464 5,96971e-17 -0,11126 
-0,390916 4,78734e-17 -0,311745 -0,216942 2,65677e-17 -0,450484 -0,153401 -0,153401 0,450484 
-0,276419 -0,276419 0,311745 -0,344689 -0,344689 0,11126 -0,344689 -0,344689 -0,11126 
-0,276419 -0,276419 -0,311745 -0,153401 -0,153401 -0,450484 -3,98516e-17 -0,216942 0,450484 
-7,18101e-17 -0,390916 0,311745 -8,95457e-17 -0,487464 0,11126 -8,95457e-17 -0,487464 -0,11126 
-7,18101e-17 -0,390916 -0,311745 -3,98516e-17 -0,216942 -0,450484 0,153401 -0,153401 0,450484 
0,276419 -0,276419 0,311745 0,344689 -0,344689 0,11126 0,344689 -0,344689 -0,11126 
0,276419 -0,276419 -0,311745 0,153401 -0,153401 -0,450484 
POLYGONS 96 384
3 2 8 0 
3 8 14 0 
3 14 20 0 
3 20 26 0 
3 26 32 0 
3 32 38 0 
3 38 44 0 
3 44 2 0 
3 7 1 13 
3 13 1 19 
3 19 1 25 
3 25 1 31 
3 31 1 37 
3 37 1 43 
3 43 1 49 
3 49 1 7 
3 2 3 9 
3 2 9 8 
3 3 4 10 
3 3 10 9 
3 4 5 11 
3 4 11 10 
3 5 6 12 
3 5 12 11 
3 6 7 13 
3 6 13 12 
3 8 9 15 
3 8 15 14 
3 9 10 16 
3 9 16 15 
3 10 11 17 
3 10 17 16 
3 11 12 18 
3 11 18 17 
3 12 13 19 
3 12 19 18 
3 14 15 21 
3 14 21 20 
3 15 16 22 
3 15 22 21 
3 16 17 23 
3 16 23 22 
3 17 18 24 
3 17 24 23 
3 18 19 25 
3 18 25 24 
3 20 21 27 
3 20 27 26 
3 21 22 28 
3 21 28 27 
3 22 23 29 
3 22 29 28 
3 23 24 30 
3 23 30 29 
3 24 25 31 
3 24 31 30 
3 26 27 33 
3 26 33 32 
3 27 28 34 
3 27 34 33 
3 28 29 35 
3 28 35 34 
3 29 30 36 
3 29 36 35 
3 30 31 37 
3 30 37 36 
3 32 33 39 
3 32 39 38 
3 33 34 40 
3 33 40 39 
3 34 35 41 
3 34 41 40 
3 35 36 42 
3 35 42 41 
3 36 37 43 
3 36 43 42 
3 38 39 45 
3 38 45 44 
3 39 40 46 
3 39 46 45 
3 40 41 47 
3 40 47 46 
3 41 42 48 
3 41 48 47 
3 42 43 49 
3 42 49 48 
3 44 45 3 
3 44 3 2 
3 45 46 4 
3 45 4 3 
3 46 47 5 
3 46 5 4 
3 47 48 6 
3 47 6 5 
3 48 49 7 
3 48 7 6 

POINT_DATA 50
NORMALS Normals float
0 0 1 0 0 -1 0,433884 0 0,900969 
0,781832 0 0,62349 0,974928 0 0,222521 0,974928 0 -0,222521 
0,781832 0 -0,62349 0,433884 0 -0,900969 0,306802 0,306802 0,900969 
0,552838 0,552838 0,62349 0,689378 0,689378 0,222521 0,689378 0,689378 -0,222521 
0,552838 0,552838 -0,62349 0,306802 0,306802 -0,900969 2,65677e-17 0,433884 0,900969 
4,78734e-17 0,781832 0,62349 5,96971e-17 0,974928 0,222521 5,96971e-17 0,974928 -0,222521 
4,78734e-17 0,781832 -0,62349 2,65677e-17 0,433884 -0,900969 -0,306802 0,306802 0,900969 
-0,552838 0,552838 0,62349 -0,689378 0,689378 0,222521 -0,689378 0,689378 -0,222521 
-0,552838 0,552838 -0,62349 -0,306802 0,306802 -0,900969 -0,433884 5,31354e-17 0,900969 
-0,781832 9,57467e-17 0,62349 -0,974928 1,19394e-16 0,222521 -0,974928 1,19394e-16 -0,222521 
-0,781832 9,57467e-17 -0,62349 -0,433884 5,31354e-17 -0,900969 -0,306802 -0,306802 0,900969 
-0,552838 -0,552838 0,62349 -0,689378 -0,689378 0,222521 -0,689378 -0,689378 -0,222521 
-0,552838 -0,552838 -0,62349 -0,306802 -0,306802 -0,900969 -7,97031e-17 -0,433884 0,900969 
-1,4362e-16 -0,781832 0,62349 -1,79091e-16 -0,974928 0,222521 -1,79091e-16 -0,974928 -0,222521 
-1,4362e-16 -0,781832 -0,62349 -7,97031e-17 -0,433884 -0,900969 0,306802 -0,306802 0,900969 
0,552838 -0,552838 0,62349 0,689378 -0,689378 0,222521 0,689378 -0,689378 -0,222521 
0,552838 -0,552838 -0,62349 0,306802 -0,306802 -0,900969 
```

**Comment by GuillaumeFavelier** [comment]
I didn't notice the comma as decimal separator but indeed [scenario 3)](https://stackoverflow.com/questions/23814541/paraview-possible-mismatch-of-datasize-with-declaration-error) seems to match your case.

Maybe changing the `LC_NUMERIC` environment variable with `export LC_NUMERIC="en_US.UTF-8"` for example could do the trick?

**Comment by supersubscript** [comment]
Indeed, changing the numeric environment resolves the issues -- thanks, @GuillaumeFavelier! @banesullivan, do you think it's worthwhile enforcing the environment using `locale`?

**Comment by banesullivan** [comment]
This is definitely quirky behavior... Thanks @supersubscript for raising this issue and @GuillaumeFavelier for your insight in solving this!

> @banesullivan, do you think it's worthwhile enforcing the environment using locale?

Perhaps... I was thinking that we could add a check for the `LC_NUMERIC` environment variable and if it is anything other than `"en_US.UTF-8"` that we could throw a warning on import for PyVista.

However, I just realized that I don't have this variable set on my computer (Mac), so I'm hesitant to add a warning the might get thrown on every user's computer. 

Was the `LC_NUMERIC` variable set to something else prior to you setting it to `"en_US.UTF-8"`?

**Comment by supersubscript** [comment]
Yes, my LC_NUMERIC was set to `"sv_SE.UTF-8`. My preferred course of action would probably be to use a decorator for functions that are doing reading/writing, similar to the answer here: https://stackoverflow.com/a/50737946

**Comment by banesullivan** [comment]
Thanks for the resource @supersubscript! Its been on my mental todo list to aggregate all of the file IO methods into a new module called `fileio` - I'll try to get a PR going soon here then we can add this context manager inside that module

**Comment by banesullivan** [comment]
@craigmillernz - perhaps this might be relevant to #239?

**Comment by banesullivan** [comment]
I'm going to close this due to inactivity and the fact that we haven't seen this be an issue for any other users in over 2 years
