### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by connorourke** [pyvista/pyvista#2363]
**Describe the bug, what's wrong, and what you expect:**

Import pyvista pulls an undefined symbol:

System Information:

OS: CentOS Linux 7
Ansys version v212 (install id - 202109161821)
PyMAPDL version (E.g. 0.59.1) 
pyvista: 0.33.3

Issue crops up when importing pyANSYS (https://github.com/pyansys/pymapdl/issues/988)

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
CRITICAL -  -  logging - handle_exception - Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/shared/home/cor22/.conda/envs/pyANSYS/lib/python3.8/site-packages/pyvista/__init__.py", line 12, in <module>
    from pyvista.plotting import *
  File "/shared/home/cor22/.conda/envs/pyANSYS/lib/python3.8/site-packages/pyvista/plotting/__init__.py", line 4, in <module>
    from .charts import Chart2D, ChartMPL, ChartBox, ChartPie
  File "/shared/home/cor22/.conda/envs/pyANSYS/lib/python3.8/site-packages/pyvista/plotting/charts.py", line 13, in <module>
    from pyvista import _vtk
  File "/shared/home/cor22/.conda/envs/pyANSYS/lib/python3.8/site-packages/pyvista/_vtk.py", line 411, in <module>
    from vtkmodules.vtkRenderingOpenGL2 import (
ImportError: /lib64/libXxf86vm.so.1: undefined symbol: _XGetRequest

```

**Comment by akaszynski** [comment]
This was resolved in https://github.com/pyansys/pymapdl/issues/988.
