### ISSUE TITLE
 No output when using VTKs legacy reader

### ISSUE THREAD

**Issue by craigmillernz** [pyvista/pyvista#239]
I'm trying to read a vtkfile created by pyBERT (resistivity inversion code, part of pyGimli) using `pv.read()`. however I get the following error:

```
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
30/05/19 - 09:08:54 - root - ERROR - vtkInformation (000001E2A3E443C0)
Traceback (most recent call last):

  File "<ipython-input-15-13da35500b22>", line 1, in <module>
    short_linear_model = pv.read(modeldir + arraydir + 'result3d.vtk')

  File "C:\Users\craigm\AppData\Local\Continuum\anaconda3\lib\site-packages\pyvista\readers.py", line 175, in read
    return read_legacy(filename)

  File "C:\Users\craigm\AppData\Local\Continuum\anaconda3\lib\site-packages\pyvista\readers.py", line 136, in read_legacy
    raise AssertionError('No output when using VTKs legacy reader')

AssertionError: No output when using VTKs legacy reader`
```

I can open the file in paraview (PVgeo).

**Comment by banesullivan** [comment]
This is quite strange - @craigmillernz, could you send me the file over Slack or post it here?

**Comment by craigmillernz** [comment]
I'll slack it to you..

**Comment by banesullivan** [comment]
Perhaps print out `modeldir + arraydir + 'result3d.vtk'` and make sure it’s correct - sometimes if the file is not valid this error gets thrown.

Todo, @banesullivan: ensure there’s a catch in the read function for when files do not exist

**Comment by craigmillernz** [comment]
Turned out to be a wrong path, not a file read issue.  A "file not found" error would be better for this kind of error.

**Comment by banesullivan** [comment]
I just added a catch in `pv.read` (e3177f8) that will throw an error if the given file does not exist
