### ISSUE TITLE
Error with pip install pyvista

### ISSUE THREAD

**Issue by bwavedev** [pyvista/pyvista#2435]
Hello.

I'm running Windows 10, with python 3.10.4
I tried to install PyVista with ```pip install pyvista```, but got an error. It says that it's probably an error with the package.

The error I got was:

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Bwave\AppData\Local\Temp\pip-install-8y_1rmha\pyvista_1c9773ba188145a9b924de5cff5a7aed\setup.py", line 45, in <module>
          long_description=open(readme_file).read(),
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 27: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by OperaRuss** [comment]
I also encountered an installation error when installing with `pip`.  Text below.  Seems to differ from the original poster's, but since there was no activity, I'm posting in case this is related to a common cause.

`ERROR: Exception:
Traceback (most recent call last):
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 203, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 237, in get_dependencies
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 237, in <listcomp>
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 243, in iter_dependencies
    requires = self.dist.iter_dependencies() if with_requires else ()
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_internal/metadata/pkg_resources.py", line 202, in iter_dependencies
    return self._dist.requires(extras)
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2736, in requires
    dm = self._dep_map
  File "/home/russ/github/polyrigid/venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _dep_map
`

**Comment by akaszynski** [comment]
Looking into this right now.

**Comment by akaszynski** [comment]
This is strange because this was fixed back in https://github.com/pyvista/pyvista/commit/33997a5f6440148f2eac05892585f99d58019702, which was three years ago. Can you please try:
```
pip install pyvista==0.34.0
```
