### ISSUE TITLE
Saving MultiBlock object with save_meshio

### ISSUE THREAD

**Issue by mcgoldba** [pyvista/pyvista#2689]
### Describe the bug, what's wrong, and what you expected.

I cannot save a MultiBlock object using the `save_meshio` function.   Instead of writing a 'wmc.msh' file, I get the following error:

`
AttributeError: 'MultiBlock' object has no attribute 'cast_to_unstructured_grid'
`

### Steps to reproduce the bug.

From an OpenFOAM case directory with mesh data (e.g. `$FOAM_TUTORIALS/Incompressible/simpleFoam/`, I add the .foam file by running the following in the (Linux) terminal:

`touch wmc.foam'

Then I try to run the following to read the mesh data and save as a '.msh' format.

```python 
 import pyvista as pv

reader = pv.OpenFOAMReader('wmc.foam')
mesh = reader.read()
pv.save_meshio('wmc.msh')

 ```

The result is:

`
 Traceback (most recent call last):
   File "foamToGmsh.py", line 26, in <module>
     pv.save_meshio('wmc.msh', mesh)
   File "/users/mgoldbac/.local/lib/python3.6/site-packages/pyvista/utilities/fileio.py", line 706, in save_meshio
     mesh = mesh.cast_to_unstructured_grid()
   File "/users/mgoldbac/.local/lib/python3.6/site-packages/pyvista/core/dataobject.py", line 41, in __getattr__
     return super().__getattribute__(item)
AttributeError: 'MultiBlock' object has no attribute 'cast_to_unstructured_grid'
`

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue May 24 14:29:26 2022 EDT

                OS : Linux
            CPU(s) : 36
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
       File system : unknown
        GPU Vendor : VMware, Inc.
      GPU Renderer : llvmpipe (LLVM 8.0, 256 bits)
       GPU Version : 3.3 (Core Profile) Mesa 19.2.6

  Python 3.6.8 (default, Sep  9 2021, 07:49:02)  [GCC 8.5.0 20210514 (Red Hat
  8.5.0-3)]

           pyvista : 0.33.3
               vtk : 8.1.2
             numpy : 1.19.5
           imageio : Module not found
           appdirs : 1.4.4
            scooby : 0.5.11
        matplotlib : 3.3.4
             PyQt5 : 5.15.0
             scipy : 1.5.4
            meshio : 4.4.6
--------------------------------------------------------------------------------
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mcgoldba** [comment]
OK.  Thanks... I'll have to find another way.
