### ISSUE TITLE
BackgroundPlotter prevents exit

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#279]
When using the `BackgroundPlotter` from a normal Python interpreter, it prevents the `exit()` command from closing the session and you have to interrupt it with `ctrl-c`. We should fix this.

```py
(dev) ➜  pyvista git:(cell-picking) python
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista as pv
>>> plotter = pv.BackgroundPlotter()
>>> exit()
^CException ignored in: <module 'threading' from '/Users/bane/anaconda3/envs/dev/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/Users/bane/anaconda3/envs/dev/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/Users/bane/anaconda3/envs/dev/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/Users/bane/anaconda3/envs/dev/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by banesullivan** [comment]
I thought this would be as simple as adding an `__exit__` method or using `atexit` to register the `closeEvent` method, but nothing is working for me
