### ISSUE TITLE
Create ClosedPlotterError

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#2884]
In [this comment](https://github.com/pyvista/pyvista/pull/2863/files/6bd6892f7b0a7c01df7501629b96f1b61994e2e0#r907183343), @adeak raised an important point: we should create a `ClosedPlotterError` and likely collect several of our "is plotter active" checks within `pyvista.Plotter`.

**Comment by adeak** [comment]
As I also noted there, we might want to be a bit more generous and have something like `ClosedResourceError` (or anything not plotter-related in name; I'm terrible at naming things). We could _also_ have a subclass of that for `ClosedPlotterError`.

E.g.:
```py
>>> import pyvista as pv
>>> pv.Plotter().write_frame()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adeak/pyvista/pyvista/plotting/plotting.py", line 3654, in write_frame
    raise RuntimeError('This plotter has not opened a movie or GIF file.')
RuntimeError: This plotter has not opened a movie or GIF file.
```

Not exactly "closed plotter" but in the very same exception ballpark.
