### ISSUE TITLE
Flying edges example broken after FFT PR

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#2901]
For some reason the exceptions are being swallowed in CI (perhaps due to caching), but the `flying-edges` example breaks after closing the first plotter as of #1953:
```bash
$ git checkout 44e5cf8cbd25aebbfc589d482f7d6af0273821bb
$ python examples/01-filter/flying_edges.py
Traceback (most recent call last):
  File "/home/adeak/examples/01-filter/flying_edges.py", line 51, in <module>
    mesh.plot(scalars=dist, smooth_shading=True, specular=5, cmap="plasma", show_scalar_bar=False)
  File "/home/adeak/pyvista/plotting/helpers.py", line 267, in plot
    return plotter.show(
  File "/home/adeak/pyvista/plotting/plotting.py", line 5497, in show
    self.close()
  File "/home/adeak/pyvista/plotting/plotting.py", line 3365, in close
    self._remove_added_scalars()
  File "/home/adeak/pyvista/plotting/plotting.py", line 4651, in _remove_added_scalars
    mesh.point_data.active_scalars_name = point_name
  File "/home/adeak/pyvista/core/datasetattributes.py", line 1167, in active_scalars_name
    dtype = self[name].dtype
  File "/home/adeak/pyvista/core/datasetattributes.py", line 215, in __getitem__
    return self.get_array(key)
  File "/home/adeak/pyvista/core/datasetattributes.py", line 541, in get_array
    raise KeyError(f'{key}')
KeyError: 'None'
$ git checkout HEAD^
$ python examples/01-filter/flying_edges.py
[no error after closing first plotter]
```

Copy-paste from the example:
```py
import numpy as np

import pyvista as pv

###############################################################################
# Spider Cage
# ~~~~~~~~~~~
# Use the marching cubes algorithm to extract the isosurface
# generated from the spider cage function.

a = 0.9


def spider_cage(x, y, z):
    x2 = x * x
    y2 = y * y
    x2_y2 = x2 + y2
    return (np.sqrt((x2 - y2) ** 2 / x2_y2 + 3 * (z * np.sin(a)) ** 2) - 3) ** 2 + 6 * (
        np.sqrt((x * y) ** 2 / x2_y2 + (z * np.cos(a)) ** 2) - 1.5
    ) ** 2


# create a uniform grid to sample the function with
n = 100
x_min, y_min, z_min = -5, -5, -3
grid = pv.UniformGrid(
    dims=(n, n, n),
    spacing=(abs(x_min) / n * 2, abs(y_min) / n * 2, abs(z_min) / n * 2),
    origin=(x_min, y_min, z_min),
)
x, y, z = grid.points.T

# sample and plot
values = spider_cage(x, y, z)
mesh = grid.contour(1, values, method='marching_cubes', rng=[1, 0])
dist = np.linalg.norm(mesh.points, axis=1)
mesh.plot(scalars=dist, smooth_shading=True, specular=5, cmap="plasma", show_scalar_bar=False)
```

Exception happens after the plotter is closed. Has to be related to the "restore scalars" logic.

Cc @akaszynski

**Comment by akaszynski** [comment]
Thanks for flagging this @adeak. I'll work on this.

**Comment by adeak** [comment]
I've taken a first look at this, and this is the crux of the issue:
```py
import numpy as np
import pyvista as pv

grid = pv.UniformGrid(dims=(5, 4, 3))
# sample and plot
values = np.arange(grid.n_points)
mesh = grid.contour([grid.n_points//2], values, method='marching_cubes')  # but not 'contour' or 'flying_edges'
print(repr(mesh.active_scalars_name), repr(mesh.active_scalars))
print(mesh.get_array(0))
#print(mesh.array_names)  # <- prevents the error
#print(mesh.point_data)  # <- also prevents the error
dist = np.arange(mesh.n_points)
mesh.plot(scalars=dist)
```

The output of the above is
```
'None' None
[30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30. 30.
 30. 30. 30. 30. 30. 30.]
```
There's an active scalars of name `'None'` (the string), but the active scalars array is `None` (the singleton instance of `NoneType`). If we uncomment either of the prints we activate scalars with name `'Unnamed_0'`.

This only happens for `'marching_cubes'`, and not for `'contour'` or `'flying_edges'`. This suggests to me that `vtkMarchingCubes()` is either buggy or pathological, and we have to work around it to fix the weird scalars. With `'flying_edges'` the active scalars are correctly set and named `'Contour Input'` as intended; this is what somehow breaks with `vtkMarchingCubes()`.

---

I've also run into a few bugs we should fix (I have these changes locally so if you open a PR I can add these there):
1. in the flying edges example we have several calls to `contour()` with `rng=[1, 0]` etc. This range should be a `[min, max]` pair, and in practice setting a reverse ordered pair like this sets both values to be the same as the first value, which is why this accidentally works. We should (i) add a check in the filter to check for the type and length of `rng`, and check for its sortedness, raise otherwise; (ii) change the `contour()` calls in the flying edges example to `contour([1], ...)` etc. where the isovalue of the contour is moved into a list as first arg and the `rng` kwarg is omitted.
2. the `scalars` kwarg in `contour()` only accepts strings and numpy arrays, and what's worse, passing in a list or a range (which should work) gets silently ignored, so the lucky case is when we get an error about no scalars being set on the data. The array case should be extended to sequences, and there should be a check for "anything else other than a string" and raised.
