### ISSUE TITLE
We don't have the ability to copy a plotter

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#3073]
### Describe the feature you would like to be added.

We don't have the ability to copy a plotter.

_Originally posted by @akaszynski in https://github.com/pyvista/pyvista/pull/3072#discussion_r929459849_

### Links to VTK Documentation, Examples, or Class Definitions.

None

### Pseudocode or Screenshots

```python 
plotter = pv.Plotter()
plotter2 = plotter.copy()
 ```

**Comment by adeak** [comment]
This won't be easy. One straightforward way to implement copying would be to do a pickle -> unpickle round.

This doesn't currently work out of the box:
```py
>>> import pickle
>>> import pyvista as pv
>>> plotter = pv.Plotter()
>>> pickle.dumps(plotter)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot pickle 'Renderer' object
>>> pickle.dumps(plotter.renderers)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot pickle 'vtkmodules.vtkRenderingOpenGL2.vtkXOpenGLRenderWindow' object
```

There are probably several VTK objects tied to the state, and we could probably only copy those if they support that themselves. And the above one doesn't look promising:
```py
>>> import vtkmodules.vtkRenderingOpenGL2
>>> [attr for attr in dir(vtkmodules.vtkRenderingOpenGL2.vtkXOpenGLRenderWindow) if 'copy' in attr.lower()]
['CopyResultFrame']
```
which doesn't look very copy-like :(

**Comment by banesullivan** [comment]
This would be a huge undertaking and would require a strong use case, which I have yet to see. With that in mind, I'm inclined to close this feature request labeling it as a known limitation until someone comes around with a strong use case and ability to support implementing it
