### ISSUE TITLE
UniformGrid cannot be cast to pointset

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#3164]
### Describe the bug, what's wrong, and what you expected.

`UniformGrid` has a `cast_to_pointset` method, but it fails when used.

### Steps to reproduce the bug.

```python
import pyvista as pv
mesh = pv.UniformGrid(dims=(5,5,5))
mesh.cast_to_pointset()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matt/pyvista/pyvista/core/dataset.py", line 2125, in cast_to_pointset
    pset.SetPoints(self.GetPoints())
  File "/home/matt/pyvista/pyvista/core/dataset.py", line 119, in __getattr__
    return super().__getattribute__(item)
AttributeError: 'UniformGrid' object has no attribute 'GetPoints'
```

### System Information

```shell
GPU Version : 4.5 (Core Profile) Mesa 20.3.5

  Python 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

           pyvista : 0.37.dev0
               vtk : 9.1.0
             numpy : 1.22.4
           imageio : 2.19.3
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.2
           IPython : 8.4.0
          colorcet : 3.0.0
           cmocean : 2.0
        ipyvtklink : 0.2.2
             scipy : 1.8.1
              tqdm : 4.64.0
            meshio : 5.3.4
        jupyterlab : 3.4.4
         pythreejs : Version unknown
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
Commenting here, but this is sort of feedback for #3242, cc @MatthewFlamm 

I think we should rewrite `cast_to_pointset` and have it on the `DataSet` class as every dataset type does fundamentally have points that a user may want to extract. IMO, this should use PyVista's `points` property to access the points (avoiding the issue of data types with implicit points like `ImageData` that do not have a `GetPoints()` method).

It should also have an option to transfer the cell data with the `cell_data_to_point_data` filter

**Comment by banesullivan** [comment]
Prototype implementation:

```py
    def cast_to_pointset(self, deep: bool = False, pass_cell_data: bool = False) -> 'pyvista.PointSet':
        """Extract the nodes of this dataset as a :class:`pyvista.PointSet`.

        Parameters
        ----------
        deep : bool, optional
            When ``True`` makes a full copy of the object.  When ``False``,
            performs a shallow copy where the points and data arrays are
            references to the original object.

        pass_cell_data : bool, optional
            Run the ``cell_data_to_point_data`` filter and pass cell data
            fields to the new pointset

        Returns
        -------
        pyvista.PointSet
            Dataset cast into a :class:`pyvista.PointSet`.

        Examples
        --------
        >>> import pyvista
        >>> mesh = pyvista.Wavelet()
        >>> pointset = mesh.cast_to_pointset()
        >>> type(pointset)
        <class 'pyvista.core.pointset.PointSet'>

        """
        pset = pyvista.PointSet()
        pset.points = self.points
        if pass_cell_data:
            self = self.cell_data_to_point_data()
        pset.GetPointData().ShallowCopy(self.GetPointData())
        if deep:
            return pset.copy(deep=True)
        return pset
```

**Comment by banesullivan** [comment]
There are a few other things we could/should do to that method. For instance, instead of running the `cell_data_to_point_data` and bundling all of it in the point data, we could still run that filter but place those data on the `cell_data` to differentiate their origin

**Comment by MatthewFlamm** [comment]
Your approach makes sense in general.

> There are a few other things we could/should do to that method. For instance, instead of running the `cell_data_to_point_data` and bundling all of it in the point data, we could still run that filter but place those data on the `cell_data` to differentiate their origin.

I'm not sure that there are valid cells in the base `vtkPointSet`.  The `GetNumberOfCellsMethod` states 

> This method always returns 0, as there are no cells in a [vtkPointSet](https://vtk.org/doc/nightly/html/classvtkPointSet.html).

**Comment by banesullivan** [comment]
Ah that's right, `PointSet` has no cells 🤦🏻‍♂️  ... for that, I'd be inclined to use `PolyData` unless there is significant overhead when compared to `PointSet`. I may want this scenario to be available as `cast_to_poly_points()`

**Comment by banesullivan** [comment]
The second implementation would look like:

```py
    def cast_to_poly_points(self, deep: bool = False, pass_cell_data: bool = False) -> 'pyvista.PolyData':
        """Extract the nodes of this dataset as a :class:`pyvista.PolyData`.

        Parameters
        ----------
        deep : bool, optional
            When ``True`` makes a full copy of the object.  When ``False``,
            performs a shallow copy where the points and data arrays are
            references to the original object.

        pass_cell_data : bool, optional
            Run the ``cell_data_to_point_data`` filter and pass cell data
            fields to the new pointset

        Returns
        -------
        pyvista.PolyData
            Dataset cast into a :class:`pyvista.PolyData`.

        Examples
        --------
        >>> from pyvista import examples
        >>> mesh = examples.load_uniform()
        >>> points = mesh.cast_to_poly_points(pass_cell_data=True)
        >>> type(points)
        <class 'pyvista.core.pointset.PolyData'>
        >>> points.n_arrays
        2

        """
        pset = pyvista.PolyData(self.points)
        if pass_cell_data:
            cell_data = self.copy()
            cell_data.clear_point_data()
            cell_data = cell_data.cell_data_to_point_data()
            pset.GetCellData().ShallowCopy(cell_data.GetPointData())
        pset.GetPointData().ShallowCopy(self.GetPointData())
        pset.active_scalars_name = self.active_scalars_name
        if deep:
            return pset.copy(deep=True)
        return pset
```
