### ISSUE TITLE
No set_active_scalars on multiblock

### ISSUE THREAD

**Issue by LukeDiederich** [pyvista/pyvista#3458]
### Describe the bug, what's wrong, and what you expected.

I found a bug!

### Steps to reproduce the bug.

```
Traceback (most recent call last):
  File "C:\Users\luked\AppData\Local\Programs\Python\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/luked/PycharmProjects/dummy.py", line 542, in <module>
    p.add_mesh_clip_plane(read)
  File "C:\Users\luked\PycharmProjects\venv\lib\site-packages\pyvista\plotting\widgets.py", line 575, in add_mesh_clip_plane
    mesh.set_active_scalars(kwargs.get('scalars', mesh.active_scalars_name))
  File "C:\Users\luked\PycharmProjects\venv\lib\site-packages\pyvista\core\dataobject.py", line 44, in __getattr__
    return super().__getattribute__(item)
AttributeError: 'MultiBlock' object has no attribute 'set_active_scalars'
```

### System Information

```shell
Test
```

**Comment by banesullivan** [comment]
Thanks for submitting - we ran into this issue together
