### ISSUE TITLE
Interactive update broken

### ISSUE THREAD

**Issue by tehrengruber** [pyvista/pyvista#3539]
### Describe the bug, what's wrong, and what you expected.

Even for a very simple example as the one attached below interactively updating a plot is broken for me. As soon as `pyvista.Plotter.update` is called I run into an error:

```
Traceback (most recent call last):
  File "/usr/share/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/share/pycharm/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "<...>/pyvista_bug.py", line 16, in <module>
    plotter.update()
  File "<...>/venv/lib/python3.10/site-packages/pyvista/plotting/plotting.py", line 1944, in update
    self.right_timer_id = self.iren.create_repeating_timer(stime)
  File "<...>/venv/lib/python3.10/site-packages/pyvista/plotting/render_window_interactor.py", line 780, in create_repeating_timer
    self.interactor.DestroyTimer(timer_id)
AttributeError: 'NoneType' object has no attribute 'DestroyTimer'
```

The origin of this error is actually this VTK `TimerEvent` that terminates the render window resulting in `self.interactor` to be `None`:

https://github.com/pyvista/pyvista/blob/af1c1bcdb7e73233ec7b0977d529973b63da1995/pyvista/plotting/plotting.py#L5803-L5806

When the timer event is executed during `update` the `_style` is `TrackballCamera` such that `self.iren.terminate_app()` is falsely executed. If I understand the comment in https://github.com/pyvista/pyvista/pull/1432 for line 5805 correctly, this has already been a problem there, but for `_style == "Context"`. The fix was to just ignore the event in that case. It is unclear to me how to trigger the code path where `self.iren.terminate_app()` is rightfully executed and equally for what `_style`s the event should be excluded. If someone can give me some input on that I am happy to open a PR with a fix.

### Steps to reproduce the bug.

```python
import pyvista as pv
from pyvista import Plotter
import time

sphere = pv.Sphere()

plotter = Plotter()
plotter.add_mesh(sphere)

# can now operate on the sphere and have it updated in the background
sphere.points *= 0.5

plotter.show(interactive_update=True)

for i in range(100):
    plotter.update()
    print(i)
    time.sleep(1)
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Nov 01 19:08:52 2022 CET
                OS : Linux
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA GeForce GTX 1650 with Max-Q Design/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 515.76
  Python 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
           pyvista : 0.37.dev0
               vtk : 9.1.20220406
             numpy : 1.22.3
           imageio : 2.17.0
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.1
         pyvistaqt : 0.9.0
             PyQt5 : 5.15.7
            meshio : 5.3.4
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
  Date: Tue Nov 01 19:09:31 2022 CET
                OS : Darwin
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon Pro 5500M OpenGL Engine
       GPU Version : 4.1 ATI-4.9.48
  Python 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0
  (clang-1400.0.29.102)]
           pyvista : 0.37.dev0
               vtk : 9.2.2
             numpy : 1.23.4
           imageio : 2.22.3
            scooby : 0.7.0
             pooch : v1.6.0
        matplotlib : 3.6.1
            meshio : 5.3.4
--------------------------------------------------------------------------------
```

**Comment by akaszynski** [comment]
I'm unable to reproduce this while on the latest commit 7195d44217df23b1bd7640ff244cf9e0f73914fb on `main`. Can you please pull and check?

**Comment by tehrengruber** [comment]
I installed from master sometime today. Some problem after I specifically installed https://github.com/pyvista/pyvista/commit/7195d44217df23b1bd7640ff244cf9e0f73914fb. Both on Linux and macOS.
