### ISSUE TITLE
Plotter update broken?

### ISSUE THREAD

**Issue by dcbr** [pyvista/pyvista#3560]
### Describe the bug, what's wrong, and what you expected.

While trying to resolve #3380 I tried running the `chart_overlays` example which seems to be broken on the latest pyvista main branch. See below code sample to reproduce. I have been OOTL for a while, so I'm not sure if it's an actual bug in the interactor code or whether certain things have changed recently to produce these interactively updated plots.

### Steps to reproduce the bug.

I condensed the `chart_overlays` example to the following lines to reproduce the bug:

```py
import pyvista as pv


p = pv.Plotter()
p.add_mesh(pv.Sphere(1), name="sphere", render=False)
p.show(auto_close=False, interactive=True, interactive_update=True)  # Show plotter
# input("Press enter to elevate sphere.")
p.add_mesh(pv.Sphere(1, center=(0, 0, 10)), name="sphere", render=False)
p.update()

p.show()  # Keep plotter open at end
```

Yielding following trace on my machine:

```
Traceback (most recent call last):
  File "C:/Users/bramd/AppData/Roaming/JetBrains/PyCharm2021.2/scratches/scratch_4.py", line 9, in <module>
    p.update()
  File "P:\python\pyvista\pyvista\plotting\plotting.py", line 1943, in update
    self.right_timer_id = self.iren.create_repeating_timer(stime)
  File "P:\python\pyvista\pyvista\plotting\render_window_interactor.py", line 780, in create_repeating_timer
    self.interactor.DestroyTimer(timer_id)
AttributeError: 'NoneType' object has no attribute 'DestroyTimer'

Process finished with exit code 1
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Sun Nov 06 17:38:28 2022 West-Europa (standaardtijd)

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.9 GiB
       Environment : Python
       File system : NTFS
        GPU Vendor : Intel
      GPU Renderer : Intel(R) HD Graphics 530
       GPU Version : 4.4.0 - Build 21.20.16.4550

  Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit
  (AMD64)]

           pyvista : 0.38.dev0
               vtk : 9.2.0
             numpy : 1.21.5
           imageio : 2.13.1
            scooby : 0.5.9
             pooch : v1.6.0
        matplotlib : 3.4.3
             PyQt5 : 5.15.6
           IPython : 7.30.1
          colorcet : 3.0.0
           cmocean : 2.0
        ipyvtklink : 0.2.1
             scipy : 1.7.3
        itkwidgets : 0.32.1
              tqdm : 4.62.3
            meshio : 4.4.6
        jupyterlab : 3.2.4
         pythreejs : Version unknown
--------------------------------------------------------------------------------
```

**Comment by akaszynski** [comment]
Unable to reproduce error on my end. @dcbr, could you propose a fix?

### System Report
```
--------------------------------------------------------------------------------
  Date: Sun Nov 06 16:20:04 2022 MST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.5 GiB
       Environment : IPython
       File system : ext4
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro K2100M/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 470.141.03

  Python 3.8.15 (default, Oct 12 2022, 19:15:16)  [GCC 11.2.0]

           pyvista : 0.37.0
               vtk : 9.2.2
             numpy : 1.22.3
           imageio : 2.19.5
            scooby : 0.7.dev0
             pooch : v1.6.0.post14+gc77fd01
        matplotlib : 3.6.0
         pyvistaqt : 0.10.dev0
             PyQt5 : 5.15.6
           IPython : 7.34.0
          colorcet : 3.0.0
           cmocean : 2.0
        ipyvtklink : 0.2.2
             scipy : 1.9.1
        itkwidgets : 0.32.1
              tqdm : 4.63.2
            meshio : 5.3.4
        jupyterlab : 3.4.7
         pythreejs : Version unknown
--------------------------------------------------------------------------------
```

**Comment by awelkie** [comment]
I'm seeing the same issue. I believe it's caused by `self.iren.terminate_app` being called prematurely here:
https://github.com/pyvista/pyvista/blame/main/pyvista/plotting/plotting.py#L5810

This line is run during the call to `p.update`. Here's my backtrace:

```
  /home/awelkie/scratch/voxel_plot/voxel_plot/__main__.py(26)<module>()
     25     # plotter.update(stime=1000, force_redraw=False)
---> 26     plotter.update()
     27     time.sleep(1)

  /home/awelkie/scratch/voxel_plot/venv/lib/python3.10/site-packages/pyvista/plotting/plotting.py(1943)update()
   1942             if (curr_time - Plotter.last_update_time) > (1.0 / update_rate):
-> 1943                 self.right_timer_id = self.iren.create_repeating_timer(stime)
   1944                 self.render()

  /home/awelkie/scratch/voxel_plot/venv/lib/python3.10/site-packages/pyvista/plotting/render_window_interactor.py(777)create_repeating_timer()
    776         if hasattr(self.interactor, 'ProcessEvents'):
--> 777             self.process_events()
    778         else:

  /home/awelkie/scratch/voxel_plot/venv/lib/python3.10/site-packages/pyvista/plotting/render_window_interactor.py(802)process_events()
    801             )
--> 802         self.interactor.ProcessEvents()
    803

  /home/awelkie/scratch/voxel_plot/venv/lib/python3.10/site-packages/pyvista/utilities/helpers.py(1194)try_callback()
   1193     try:
-> 1194         func(*args)
   1195     except Exception:

  /home/awelkie/scratch/voxel_plot/venv/lib/python3.10/site-packages/pyvista/plotting/plotting.py(5810)on_timer()
   5809             if event_id == 'TimerEvent' and self.iren._style != "Context":
-> 5810                 self.iren.terminate_app()
   5811

> /home/awelkie/scratch/voxel_plot/venv/lib/python3.10/site-packages/pyvista/plotting/render_window_interactor.py(829)terminate_app()
    828         """Terminate the app."""
--> 829         if self.initialized:
    830

ipdb> up
> /home/awelkie/scratch/voxel_plot/venv/lib/python3.10/site-packages/pyvista/plotting/plotting.py(5810)on_timer()
   5809             if event_id == 'TimerEvent' and self.iren._style != "Context":
-> 5810                 self.iren.terminate_app()
   5811


ipdb> self.iren._style
'TrackballCamera'

```

**Comment by dcbr** [comment]
I'm a bit short on time at the moment, but I'll try to further investigate next week. Maybe it's Windows related if you cannot reproduce it. It has indeed something to do with the `on_timer` callback being executed earlier than previously as @awelkie pointed out. I have always wondered what that callback is supposed to achieve, as I had to add an exception (`self.iren._style != "Context"`) while working on the charts functionality earlier to prevent early closure of the plotting window (see https://github.com/pyvista/pyvista/pull/1432/files#r675993750).

**Comment by bibbygoodwin** [comment]
I'm having the same issue. M1 Mac, Python 3.10, Pyvista version 0.37.0. 

The weirdest thing is that the script was running fine. Then, despite having made no changes, I started getting the above error when calling `pl.update()`. It also seems to be a stochastic problem: sometimes I can render about 10 frames before this error occurs, sometimes just the first one.
