### ISSUE TITLE
Exception with 0-d np.array dataset attribute 

### ISSUE THREAD

**Issue by eudoxos** [pyvista/pyvista#3639]
I am getting exception when attribute being added to the dataset is a 0-d np.array (such as in `A=np.array(1,np.int64)` where `A.ndim==0` and `A.shape==()`).

```py
    poly.add_field_data(A,'TimeValue')
  File "C:\Program Files\Python310\lib\site-packages\pyvista\core\dataobject.py", line 356, in add_field_data
    self.field_data.set_array(array, name, deep_copy=deep)
  File "C:\Program Files\Python310\lib\site-packages\pyvista\core\datasetattributes.py", line 618, in set_array
    vtk_arr = self._prepare_array(data, name, deep_copy)
  File "C:\Program Files\Python310\lib\site-packages\pyvista\core\datasetattributes.py", line 797, in _prepare_array
    array_len = data.shape[0] if isinstance(data, np.ndarray) else 1
IndexError: tuple index out of range
```

https://github.com/pyvista/pyvista/blob/728a71f501beaa83296395cf1450733ac895ac2d/pyvista/core/datasetattributes.py#L745

I can fix it in my code, but since pyvista is doing some input validation, this could also be covered, especially as `ndim==0` case is considered just a few lines below:

https://github.com/pyvista/pyvista/blob/728a71f501beaa83296395cf1450733ac895ac2d/pyvista/core/datasetattributes.py#L748

**Comment by eudoxos** [comment]
I checked better and it is a regression introduced [here](https://github.com/pyvista/pyvista/pull/2754/files#diff-f428ec576e878755950fff9ff1ba8b794a6085ec4e6c2e9a54fdb3666ba72e155) (PR #2754), this is the current offending line:

https://github.com/pyvista/pyvista/blob/3616866543079780cfb59c44834fe71918bf1fd8/pyvista/core/datasetattributes.py#L738

Thus any scalar (such as `int`, as in my case) would be converted to 0-d array. The `isinstance(data,np.ndarray)` seems to be redundant, as data will be always a ndarray. Thus the line should read (as far as I can see):

```py
assert isinstance(data,np.ndarray)
array_len = data.shape[0] if data.ndim>0 else 1
```

**Comment by adeak** [comment]
Thanks for the report, and for looking into it. This is definitely a bug.

There are other weird things going on there:
https://github.com/pyvista/pyvista/blob/cc63b7d33f4f1ffb87c05a640cec4688d0f7a2ff/pyvista/core/datasetattributes.py#L746-L750

This seems to assume that scalars are floats. Even though field data can even be an array of strings, even according to [our own docs](https://docs.pyvista.org/user-guide/data_model.html#field-data). So I think this needs a closer looking at.

**Comment by adeak** [comment]
I'm starting to think that we should skip `_prepare_array()/_patch_type()` etc. altogether for field data, because some other things it should be doing doesn't work:
```py
>>> mesh = pv.Sphere()
>>> mesh.field_data['cplex'] = [1 + 2j]
>>> mesh.field_data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adeak/pyvista/pyvista/core/datasetattributes.py", line 143, in __repr__
    for i, (name, array) in enumerate(self.items()):
  File "/home/adeak/pyvista/pyvista/core/datasetattributes.py", line 922, in items
    return list(zip(self.keys(), self.values()))
  File "/home/adeak/pyvista/pyvista/core/datasetattributes.py", line 975, in values
    return [self.get_array(name) for name in self.keys()]
  File "/home/adeak/pyvista/pyvista/core/datasetattributes.py", line 975, in <listcomp>
    return [self.get_array(name) for name in self.keys()]
  File "/home/adeak/pyvista/pyvista/core/datasetattributes.py", line 486, in get_array
    return self._patch_type(narray)
  File "/home/adeak/pyvista/pyvista/core/datasetattributes.py", line 500, in _patch_type
    narray = narray.squeeze()
RuntimeError: ndarray subclass __array_wrap__ method returned an object which was not an instance of an ndarray subclass
```
And we probably want to have very few requirements for field data.

**Comment by adeak** [comment]
OK, the error in my previous comment is an unrelated issue, see https://github.com/pyvista/pyvista/issues/3653...
