### ISSUE TITLE
Towards a single, PyVista/VTK-native Jupyter Backend

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#3690]
I'm working to completely overhaul the state of PyVista's Jupyter backends to provide a new, single "PyVista Backend"

The new backend will be included in #3385 as it will initially be based on `trame`.

In later pull requests, I will deprecate the other backends in the following fashion to move users towards a single backend that we will maintain and support moving forward.

#### Full deprecation and removal (one PR)

- `ipyvtklink` - Full deprecation and removal as it is entirely replaced by the "server" variant of the new backend with much better performance. Usage of this will be automatically replaced with the new backend's server variant.
- `itkwidgets`/`PlotterITK` - Full deprecation and removal (not widely used as far as I can tell)

#### Deprecation and notice of future removal (one PR)

- `panel` - Deprecation notice of no further support and future removal
- `ipygany` - Deprecation notice of no further support and future removal

#### No Action

- `pythreejs` - This backend will remain untouched for now. It's the only backend that does not require a virtual frame buffer which is quite significant for some edge cases. Though we need to look into issues like https://github.com/pyvista/pyvista/issues/3221
- The `static` and `none` backend options will remain as-is.

-------

The new "PyVista Backend" will initially be built on Kitware's `trame` - a new framework for building dynamic web applications with Python with great support for VTK. Under the hood, trame uses features embedded in VTK Python and `wslink` to handle two modes of client-server 3D rendering interaction: 

1. **server-side rendering** with screenshots streaming the client (this is effectively the same as `ipyvtklink` just much improved)
2. **client-side rendering** where a scene graph's state is synchronized between server and client. This is rendered with VTK.js on the client side and requires a `vtkRenderWindow` on the server.

The initial PR will bundle this into a minimally working state. While I'm calling this "minimal" (MVP), it is not minimal in terms of feature completeness but rather minimal in the architecture sense. Initially, this will fully bring in `trame` and all of its dependencies (fairly lightweight). I will later iterate on the architecture to reduce the dependencies and eventually use the Jupyter comms over `wslink` and `jupyter-server-proxy`.

Further details on the new backend will be outlined in #3385 as I wrap up the implementation (in the coming weeks).

## Name of new backend

I'd like for this new backend to have a general name to indicate that it is the main Jupyter backend for PyVista. Considering it has two variants (or modes), I'm thinking of using the names `client` and `server`.

```py
mesh.plot(jupyter_backend='client')  # <--- client-side rendering with state synchronization
```

```py
mesh.plot(jupyter_backend='server')  # <--- server-side rendering (streams a screenshot)
```

```py
mesh.plot(jupyter_backend='static')  # <--- Static screenshot output
```

```py
mesh.plot(jupyter_backend='none')  # <--- No op
```

Thoughts and opinions on this naming would be much appreciated! Please chime in below.

-----

## Related Issues

I've dug through a lot of open issues related to different backends, and I'm trying to track them all here and see what I can do to resolve or address most/all of them. If something is not captured here, please post it in this thread.

### Issues that will be resolved by this work:

- https://github.com/pyvista/pyvista/issues/2940 - this will be supported by the new backend
- https://github.com/pyvista/pyvista/issues/3482 - this will be supported by the new backend
- https://github.com/pyvista/pyvista/issues/3274 - The new backend will not leverage `ipywidgets` (yet? could in a later iteration though)
- https://github.com/pyvista/pyvista/issues/1635 - these backends will be removed
- https://github.com/pyvista/pyvista/issues/1624 - PlotterITK will be removed
- https://github.com/pyvista/pyvista/issues/1205 - PlotterITK will be removed
- https://github.com/pyvista/pyvista/issues/785 - PlotterITK will be removed
- https://github.com/pyvista/pyvista/issues/714 - PlotterITK will be removed
- https://github.com/pyvista/pyvista/issues/3695 - This should be handled by the new backend
- https://github.com/pyvista/pyvista/issues/3752 - Triangle strips will be supported

### Further work that should come after this:

- https://github.com/pyvista/pyvista/issues/184

### To look into (this is a todo list for myself)

- [x] https://github.com/pyvista/pyvista/issues/3221
- [x] https://github.com/pyvista/pyvista/issues/2962 - can the new client backend support labels?
- [x] https://github.com/pyvista/pyvista/issues/3091 - can VTK.js and client-side rendering support this?
- [x] https://github.com/pyvista/pyvista/issues/1698
- [x] https://github.com/pyvista/pyvista/issues/3439
- [x] https://github.com/pyvista/pyvista/issues/3360

**Comment by francesco-ballarin** [comment]
Thanks @banesullivan, looking forward to the new jupyter backend!

Can you comment on whether the new backend will make it easier to use pyvista non-static jupyter backends on online notebook services, such as Google Colab or similar?
Being headless environments, `pythreejs` seemed to be a good fit. Yet, the reality is that there are still huge limitations (and not so much upstream interest) in its support on such services, see e.g. https://github.com/jupyter-widgets/pythreejs/issues/388, https://github.com/googlecolab/colabtools/issues/3159, https://github.com/Kaggle/docker-python/issues/1190 for a few issues I opened myself on that topic.

**Comment by banesullivan** [comment]
Hi @francesco-ballarin, this new backend will have good compatibility with online services like Binder, etc. 

The new backend will have a mode that will do purely client-side rendering, though like all of the client-side rendering backends before it, it will not be fully featured. However, it will be able to run without a virtual frame buffer. As I wrap up the PR that introduces the new backend, I plan to include some docs/examples that demonstrate all the different usage scenarios.

Further, I want to point out that VTK is soon to start publishing OSMesa wheel variants that will make plotting in headless environments a whole lot easier.

Stay tuned!

**Comment by francesco-ballarin** [comment]
Thanks @banesullivan. Feel free to ping me when the new Jupyter backend is ready to be tested, and I will do so on Google Colab within [my FEM on Colab](https://fem-on-colab.github.io/) project.
With [PlotterITK gone](https://github.com/pyvista/pyvista/pull/3737) (and [broken anyways](https://github.com/InsightSoftwareConsortium/itkwidgets/issues/588)), and `pythreejs` not working (see issues linked above), currently no interactive jupyter backend can be used there.

**Comment by francesco-ballarin** [comment]
Another corner case that you may be willing to consider: when running in jupyter notebooks and exporting to file, will the widget/plot still be shown and interactive when the notebook is exported to html? For instance, if I remember correctly former plots with PlotterITK where not showing after an html export, while pythreejs plots do show, instead.

**Comment by jorgensd** [comment]
I cannot get `trame` to work with `docker/jupyterlab`.
MWE:
1. Create docker environment with:
```bash
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y python3-pip git
RUN apt-get install -y libgl1-mesa-glx libxrender1
RUN python3 -m pip install pip setuptools -U

ENV DEB_PYTHON_INSTALL_LAYOUT=deb_system
RUN python3 -m pip install jupyter matplotlib 'jupyterlab>=3' ipywidgets 'pyvista[all,jupyter,trame] @ git+https://github.com/pyvista/pyvista@main'
ENV PYVISTA_TRAME_SERVER_PROXY_PREFIX='/proxy/'
ENV PYVISTA_TRAME_SERVER_PROXY_ENABLED="True"
ENTRYPOINT ["jupyter", "lab", "--ip", "0.0.0.0", "--no-browser", "--allow-root"]

```
2. Build with
```bash
 docker build -t test_trame -f Dockerfile .
```
3. Open lab interface with:
```
docker run -ti --network=host -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd):/root/shared -w /root/shared --rm --shm-size=512m test_trame
```
4. Run notebook with following code:
```python
import pyvista as pv
print(pv.global_theme.trame.server_proxy_enabled)
print(pv.global_theme.trame.server_proxy_prefix)
pv.set_jupyter_backend("trame")
plotter = pv.Plotter(notebook=True)
sphere = pv.Sphere()
actor = plotter.add_mesh(sphere)
plotter.set_background('lightgrey')
plotter.show()
```
Result is nothing showing
![trame](https://user-images.githubusercontent.com/8554300/215585406-e8812e58-c01c-4fcb-ab40-87609b2c7b5d.png)

**Comment by jorgensd** [comment]
Pinning ` ipywidgets==7.7.2` gives a long error message:
```bash
[E 2023-01-30 20:29:53.928 ServerApp] Uncaught exception GET /proxy/36471/__trame_vuetify/fonts/materialdesignicons-webfont.ad0f7b3f.woff2 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/__trame_vuetify/fonts/materialdesignicons-webfont.ad0f7b3f.woff2', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/websocket.py", line 91, in get
        return await self.http_get(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 506, in http_get
        return await self.proxy(port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 323, in proxy
        response = await client.fetch(req, raise_error=False)
      File "/usr/lib/python3/dist-packages/tornado/iostream.py", line 869, in _read_to_buffer
        bytes_read = self.read_from_fd(buf)
      File "/usr/lib/python3/dist-packages/tornado/iostream.py", line 1138, in read_from_fd
        return self.socket.recv_into(buf, len(buf))
    ConnectionResetError: [Errno 104] Connection reset by peer
[E 2023-01-30 20:29:53.930 ServerApp] {
      "Host": "127.0.0.1:8888",
      "Accept": "application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8",
      "Referer": "http://127.0.0.1:8888/proxy/36471/__trame_vuetify/trame-vuetify.css",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0"
    }
[E 2023-01-30 20:29:53.930 ServerApp] 500 GET /proxy/36471/__trame_vuetify/fonts/materialdesignicons-webfont.ad0f7b3f.woff2 (aec8fddf2478464f92e75895e10ea77b@127.0.0.1) 179.83ms referer=http://127.0.0.1:8888/proxy/36471/__trame_vuetify/trame-vuetify.css
[E 2023-01-30 20:29:53.952 ServerApp] Uncaught exception GET /proxy/36471/__trame_vuetify/fonts/materialdesignicons-webfont.fabeafb8.woff (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/__trame_vuetify/fonts/materialdesignicons-webfont.fabeafb8.woff', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/websocket.py", line 91, in get
        return await self.http_get(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 506, in http_get
        return await self.proxy(port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 323, in proxy
        response = await client.fetch(req, raise_error=False)
    ConnectionRefusedError: [Errno 111] Connection refused
[E 2023-01-30 20:29:53.954 ServerApp] {
      "Host": "127.0.0.1:8888",
      "Accept": "application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8",
      "Referer": "http://127.0.0.1:8888/proxy/36471/__trame_vuetify/trame-vuetify.css",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0"
    }
[E 2023-01-30 20:29:53.954 ServerApp] 500 GET /proxy/36471/__trame_vuetify/fonts/materialdesignicons-webfont.fabeafb8.woff (aec8fddf2478464f92e75895e10ea77b@127.0.0.1) 3.27ms referer=http://127.0.0.1:8888/proxy/36471/__trame_vuetify/trame-vuetify.css
[E 2023-01-30 20:29:53.960 ServerApp] Uncaught exception GET /proxy/36471/__trame_vuetify/fonts/materialdesignicons-webfont.f5b84261.ttf (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/__trame_vuetify/fonts/materialdesignicons-webfont.f5b84261.ttf', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/websocket.py", line 91, in get
        return await self.http_get(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 506, in http_get
        return await self.proxy(port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 323, in proxy
        response = await client.fetch(req, raise_error=False)
    ConnectionRefusedError: [Errno 111] Connection refused
[E 2023-01-30 20:29:53.961 ServerApp] {
      "Host": "127.0.0.1:8888",
      "Accept": "application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8",
      "Referer": "http://127.0.0.1:8888/proxy/36471/__trame_vuetify/trame-vuetify.css",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0"
    }
[E 2023-01-30 20:29:53.961 ServerApp] 500 GET /proxy/36471/__trame_vuetify/fonts/materialdesignicons-webfont.f5b84261.ttf (aec8fddf2478464f92e75895e10ea77b@127.0.0.1) 2.94ms referer=http://127.0.0.1:8888/proxy/36471/__trame_vuetify/trame-vuetify.css
[I 2023-01-30 20:29:54.448 ServerApp] Trying to establish websocket connection to ws://localhost:36471/ws
[E 2023-01-30 20:29:54.450 ServerApp] Uncaught exception GET /proxy/36471/ws (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 509, in open
        return await self.proxy_open('localhost', port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 459, in proxy_open
        await start_websocket_connection()
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 450, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
    ConnectionRefusedError: [Errno 111] Connection refused
[I 2023-01-30 20:29:54.947 ServerApp] Trying to establish websocket connection to ws://localhost:36471/ws
[E 2023-01-30 20:29:54.948 ServerApp] Uncaught exception GET /proxy/36471/ws (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 509, in open
        return await self.proxy_open('localhost', port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 459, in proxy_open
        await start_websocket_connection()
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 450, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
    ConnectionRefusedError: [Errno 111] Connection refused
[I 2023-01-30 20:29:55.447 ServerApp] Trying to establish websocket connection to ws://localhost:36471/ws
[E 2023-01-30 20:29:55.449 ServerApp] Uncaught exception GET /proxy/36471/ws (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 509, in open
        return await self.proxy_open('localhost', port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 459, in proxy_open
        await start_websocket_connection()
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 450, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
    ConnectionRefusedError: [Errno 111] Connection refused
[I 2023-01-30 20:29:55.947 ServerApp] Trying to establish websocket connection to ws://localhost:36471/ws
[E 2023-01-30 20:29:55.949 ServerApp] Uncaught exception GET /proxy/36471/ws (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 509, in open
        return await self.proxy_open('localhost', port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 459, in proxy_open
        await start_websocket_connection()
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 450, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
    ConnectionRefusedError: [Errno 111] Connection refused
[I 2023-01-30 20:29:56.348 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2023-01-30 20:29:56.348 ServerApp] kernel 90a0b050-f09e-42a6-9617-c92566c41f6d restarted
[W 2023-01-30 20:29:56.348 ServerApp] kernel 90a0b050-f09e-42a6-9617-c92566c41f6d restarted
[I 2023-01-30 20:29:56.354 ServerApp] Starting buffering for 90a0b050-f09e-42a6-9617-c92566c41f6d:2671e250-3f5c-4962-941d-957fb6d29426
[I 2023-01-30 20:29:56.362 ServerApp] Connecting to kernel 90a0b050-f09e-42a6-9617-c92566c41f6d.
[I 2023-01-30 20:29:56.373 ServerApp] Connecting to kernel 90a0b050-f09e-42a6-9617-c92566c41f6d.
[I 2023-01-30 20:29:56.449 ServerApp] Trying to establish websocket connection to ws://localhost:36471/ws
[E 2023-01-30 20:29:56.450 ServerApp] Uncaught exception GET /proxy/36471/ws (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 509, in open
        return await self.proxy_open('localhost', port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 459, in proxy_open
        await start_websocket_connection()
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 450, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
    ConnectionRefusedError: [Errno 111] Connection refused
[I 2023-01-30 20:29:56.947 ServerApp] Trying to establish websocket connection to ws://localhost:36471/ws
[E 2023-01-30 20:29:56.949 ServerApp] Uncaught exception GET /proxy/36471/ws (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 509, in open
        return await self.proxy_open('localhost', port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 459, in proxy_open
        await start_websocket_connection()
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 450, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
    ConnectionRefusedError: [Errno 111] Connection refused
[I 2023-01-30 20:29:57.447 ServerApp] Trying to establish websocket connection to ws://localhost:36471/ws
[E 2023-01-30 20:29:57.449 ServerApp] Uncaught exception GET /proxy/36471/ws (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 509, in open
        return await self.proxy_open('localhost', port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 459, in proxy_open
        await start_websocket_connection()
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 450, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
    ConnectionRefusedError: [Errno 111] Connection refused
[I 2023-01-30 20:29:57.948 ServerApp] Trying to establish websocket connection to ws://localhost:36471/ws
[E 2023-01-30 20:29:57.949 ServerApp] Uncaught exception GET /proxy/36471/ws (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 509, in open
        return await self.proxy_open('localhost', port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 459, in proxy_open
        await start_websocket_connection()
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 450, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
    ConnectionRefusedError: [Errno 111] Connection refused
[I 2023-01-30 20:29:58.448 ServerApp] Trying to establish websocket connection to ws://localhost:36471/ws
[E 2023-01-30 20:29:58.450 ServerApp] Uncaught exception GET /proxy/36471/ws (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 509, in open
        return await self.proxy_open('localhost', port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 459, in proxy_open
        await start_websocket_connection()
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 450, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
    ConnectionRefusedError: [Errno 111] Connection refused
[I 2023-01-30 20:29:58.949 ServerApp] Trying to establish websocket connection to ws://localhost:36471/ws
[E 2023-01-30 20:29:58.950 ServerApp] Uncaught exception GET /proxy/36471/ws (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/proxy/36471/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 509, in open
        return await self.proxy_open('localhost', port, proxied_path)
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 459, in proxy_open
        await start_websocket_connection()
      File "/usr/lib/python3/dist-packages/jupyter_server_proxy/handlers.py", line 450, in start_websocket_connection
        self.ws = await pingable_ws_connect(request=request,
    ConnectionRefusedError: [Errno 111] Connection refused
````
![trame_pinned](https://user-images.githubusercontent.com/8554300/215588669-6bf3f9c5-faae-4761-86f5-089459c37224.png)

**Comment by banesullivan** [comment]
@jorgensd, would you please open a new issue for this? Looking into it now though.

(this issue is going to be resolved by a pending PR)

**Comment by banesullivan** [comment]
@jorgensd, I just built your Dockerfile and all works as expected. The only difference is that I'm not doing the dospaly forwarding that you are doing and instead using xvfb
![Screen Shot 2023-01-30 at 1 52 10 PM](https://user-images.githubusercontent.com/22067021/215592412-a8eb4eca-a820-4804-a57a-ddc6b1880b42.png)

**Comment by jorgensd** [comment]
> @jorgensd, would you please open a new issue for this? Looking into it now though.
> 
> 
> 
> (this thread is going to be resolved by a pending PR)

Done
