### ISSUE TITLE
Missing ``ipywidgets`` package

### ISSUE THREAD

**Issue by germa89** [pyvista/pyvista#3941]
### Describe the bug, what's wrong, and what you expected.

After installing the last version, I get:

```pycon
Python 3.11.1 (main, Dec 23 2022, 09:28:24) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/german.ayuso/trashy/venvtrash/lib/python3.11/site-packages/pyvista/__init__.py", line 9, in <module>
    from pyvista import trame
  File "/Users/german.ayuso/trashy/venvtrash/lib/python3.11/site-packages/pyvista/trame/__init__.py", line 2, in <module>
    from pyvista.trame.jupyter import launch_server, show_trame, elegantly_launch
  File "/Users/german.ayuso/trashy/venvtrash/lib/python3.11/site-packages/pyvista/trame/jupyter.py", line 7, in <module>
    from ipywidgets import widgets
ModuleNotFoundError: No module named 'ipywidgets'
```

Using Mac OS (M2-Ventura 13.1)

### Steps to reproduce the bug.

Just update and import pyvista

```py
import pyvista
```

### System Information

```shell
NA
```

**Comment by banesullivan** [comment]
0.38.1 should be out in the next 15 minutes -- sorry this slipped through the cracks!
