### ISSUE TITLE
Fresh install -> ImportError: DLL load failed while importing _imaging: The specified module could not be found

### ISSUE THREAD

**Issue by fusentasticus** [pyvista/pyvista#4427]
### Discussed in https://github.com/pyvista/pyvista/discussions/4426

<div type='discussions-op-text'>

<sup>Originally posted by **fusentasticus** May 15, 2023</sup>
Hi - in a fresh Anaconda installation on Windows 11 (Python 3.10.11, 64-bit) with scipy installed, I go to my shell to install vista & meshfix:

conda install -c conda-forge pyvista
conda install -c conda-forge pymeshfix

Then I start a python program as  

```
C:/Users/fusentasticus/anaconda3/envs/scipy/python.exe "c:/Users/fusentasticus/Dropbox/x.py"
```
But it chokes right away on the pyvista import:
```
Traceback (most recent call last):                                                                                        
  File "c:\Users\fusentasticus\Dropbox\x.py", line 2, in <module>
    import pyvista as pv                                                                                                  
  File "C:\Users\fusentasticus\anaconda3\envs\scipy\lib\site-packages\pyvista\__init__.py", line 10, in <module>
    from pyvista.plotting import *
  File "C:\Users\fusentasticus\anaconda3\envs\scipy\lib\site-packages\pyvista\plotting\__init__.py", line 4, in <module>
    from .charts import Chart, Chart2D, ChartMPL, ChartBox, ChartPie
  File "C:\Users\fusentasticus\anaconda3\envs\scipy\lib\site-packages\pyvista\plotting\charts.py", line 10, in <module>
    from matplotlib.backends.backend_agg import FigureCanvasAgg
  File "C:\Users\fusentasticus\anaconda3\envs\scipy\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\Users\fusentasticus\anaconda3\envs\scipy\lib\site-packages\matplotlib\rcsetup.py", line 24, in <module>
    from matplotlib import _api, animation, cbook
  File "C:\Users\fusentasticus\anaconda3\envs\scipy\lib\site-packages\matplotlib\animation.py", line 34, in <module>
    from PIL import Image
  File "C:\Users\fusentasticus\anaconda3\envs\scipy\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.
```

Would you have any recommendations? Thanks!

-------------

Here's the thinking during the conda installs:
```
(scipy) PS C:\Users\fusentasticus> conda install -c conda-forge pyvista
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\fusentasticus\anaconda3\envs\scipy

  added / updated specs:
    - pyvista


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.5.7   |       h56e8100_0         145 KB  conda-forge
    certifi-2023.5.7           |     pyhd8ed1ab_0         149 KB  conda-forge
    colorama-0.4.6             |     pyhd8ed1ab_0          25 KB  conda-forge
    curl-7.88.1                |       h2bbff1b_0         147 KB
    cycler-0.11.0              |     pyhd8ed1ab_0          10 KB  conda-forge
    double-conversion-3.2.0    |       h0e60522_0         116 KB  conda-forge
    eigen-3.4.0                |       h2d74725_0         1.2 MB  conda-forge
    expat-2.5.0                |       h63175ca_1         221 KB  conda-forge
    ffmpeg-4.2.3               |       ha925a31_0        23.2 MB  conda-forge
    freetype-2.10.4            |       h546665d_1         489 KB  conda-forge
    gl2ps-1.4.2                |       h0597ee9_0          74 KB  conda-forge
    glew-2.2.0                 |       hd77b12b_0         895 KB
    hdf4-4.2.15                |       h0e5069d_3         1.1 MB  conda-forge
    hdf5-1.10.6                |nompi_h5268f04_1114        19.6 MB  conda-forge
    jpeg-9e                    |       h8ffe710_2         366 KB  conda-forge
    jsoncpp-1.9.4              |       h2d74725_3         956 KB  conda-forge
    kiwisolver-1.4.4           |  py310h476a331_0          61 KB  conda-forge
    libcurl-7.88.1             |       h86230a5_0         328 KB
    libexpat-2.5.0             |       h63175ca_1         135 KB  conda-forge
    libiconv-1.17              |       h8ffe710_0         698 KB  conda-forge
    libnetcdf-4.8.1            |nompi_hf689e7d_100         674 KB  conda-forge
    libssh2-1.10.0             |       h680486a_2         227 KB  conda-forge
    libtheora-1.1.1            |    h8d14728_1005         201 KB  conda-forge
    libvorbis-1.3.7            |       h0e60522_0         267 KB  conda-forge
    libwebp-1.2.4              |       h2bbff1b_0          67 KB
    libxml2-2.10.3             |       h0ad7f3c_0         2.9 MB
    libzip-1.8.0               |       h49b8836_0          95 KB
    loguru-0.7.0               |  py310h5588dad_0          93 KB  conda-forge
    matplotlib-base-3.4.3      |  py310h79a7439_2         7.3 MB  conda-forge
    pcre-8.45                  |       h0e60522_0         518 KB  conda-forge
    proj-6.2.1                 |       h3758d61_0         7.9 MB
    pyparsing-3.0.9            |     pyhd8ed1ab_0          79 KB  conda-forge
    python-dateutil-2.8.2      |     pyhd8ed1ab_0         240 KB  conda-forge
    python_abi-3.10            |          2_cp310           4 KB  conda-forge
    pyvista-0.39.0             |     pyhd8ed1ab_0         1.3 MB  conda-forge
    qt-5.15.7                  |       haa95532_0           9 KB
    scooby-0.7.2               |     pyhd8ed1ab_0          20 KB  conda-forge
    six-1.16.0                 |     pyh6c4a22f_0          14 KB  conda-forge
    tornado-6.2                |  py310he2412df_0         666 KB  conda-forge
    utfcpp-3.2.3               |       h57928b3_0          12 KB  conda-forge
    vtk-9.0.3                  |py310ha6ea5fc_203        24.7 MB
    win32_setctime-1.1.0       |     pyhd8ed1ab_0           7 KB  conda-forge
    zstd-1.5.5                 |       hd43e919_0         682 KB
    ------------------------------------------------------------
                                           Total:        97.7 MB

The following NEW packages will be INSTALLED:

  colorama           conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0
  curl               pkgs/main/win-64::curl-7.88.1-h2bbff1b_0
  cycler             conda-forge/noarch::cycler-0.11.0-pyhd8ed1ab_0
  double-conversion  conda-forge/win-64::double-conversion-3.2.0-h0e60522_0
  eigen              conda-forge/win-64::eigen-3.4.0-h2d74725_0
  expat              conda-forge/win-64::expat-2.5.0-h63175ca_1
  ffmpeg             conda-forge/win-64::ffmpeg-4.2.3-ha925a31_0
  freetype           conda-forge/win-64::freetype-2.10.4-h546665d_1
  gl2ps              conda-forge/win-64::gl2ps-1.4.2-h0597ee9_0
  glew               pkgs/main/win-64::glew-2.2.0-hd77b12b_0
  glib               pkgs/main/win-64::glib-2.69.1-h5dc1a3c_2
  gst-plugins-base   pkgs/main/win-64::gst-plugins-base-1.18.5-h9e645db_0
  gstreamer          pkgs/main/win-64::gstreamer-1.18.5-hd78058f_0
  hdf4               conda-forge/win-64::hdf4-4.2.15-h0e5069d_3
  hdf5               conda-forge/win-64::hdf5-1.10.6-nompi_h5268f04_1114
  icu                pkgs/main/win-64::icu-58.2-ha925a31_3
  jpeg               conda-forge/win-64::jpeg-9e-h8ffe710_2
  jsoncpp            conda-forge/win-64::jsoncpp-1.9.4-h2d74725_3
  kiwisolver         conda-forge/win-64::kiwisolver-1.4.4-py310h476a331_0
  lerc               pkgs/main/win-64::lerc-3.0-hd77b12b_0
  libclang           pkgs/main/win-64::libclang-12.0.0-default_h627e005_2
  libcurl            pkgs/main/win-64::libcurl-7.88.1-h86230a5_0
  libdeflate         pkgs/main/win-64::libdeflate-1.17-h2bbff1b_0
  libexpat           conda-forge/win-64::libexpat-2.5.0-h63175ca_1
  libiconv           conda-forge/win-64::libiconv-1.17-h8ffe710_0
  libnetcdf          conda-forge/win-64::libnetcdf-4.8.1-nompi_hf689e7d_100
  libogg             pkgs/main/win-64::libogg-1.3.5-h2bbff1b_1
  libpng             pkgs/main/win-64::libpng-1.6.39-h8cc25b3_0
  libssh2            conda-forge/win-64::libssh2-1.10.0-h680486a_2
  libtheora          conda-forge/win-64::libtheora-1.1.1-h8d14728_1005
  libtiff            pkgs/main/win-64::libtiff-4.5.0-h6c2663c_2
  libvorbis          conda-forge/win-64::libvorbis-1.3.7-h0e60522_0
  libwebp            pkgs/main/win-64::libwebp-1.2.4-h2bbff1b_0
  libwebp-base       pkgs/main/win-64::libwebp-base-1.2.4-h2bbff1b_1
  libxml2            pkgs/main/win-64::libxml2-2.10.3-h0ad7f3c_0
  libzip             pkgs/main/win-64::libzip-1.8.0-h49b8836_0
  loguru             conda-forge/win-64::loguru-0.7.0-py310h5588dad_0
  lz4-c              pkgs/main/win-64::lz4-c-1.9.4-h2bbff1b_0
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.4.3-py310h79a7439_2
  pcre               conda-forge/win-64::pcre-8.45-h0e60522_0
  pillow             pkgs/main/win-64::pillow-9.4.0-py310hd77b12b_0
  proj               pkgs/main/win-64::proj-6.2.1-h3758d61_0
  pyparsing          conda-forge/noarch::pyparsing-3.0.9-pyhd8ed1ab_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python_abi         conda-forge/win-64::python_abi-3.10-2_cp310
  pyvista            conda-forge/noarch::pyvista-0.39.0-pyhd8ed1ab_0
  qt                 pkgs/main/win-64::qt-5.15.7-haa95532_0
  qt-main            pkgs/main/win-64::qt-main-5.15.2-he8e5bd7_7
  qt-webengine       pkgs/main/win-64::qt-webengine-5.15.9-hb9a9bb5_5
  scooby             conda-forge/noarch::scooby-0.7.2-pyhd8ed1ab_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  tornado            conda-forge/win-64::tornado-6.2-py310he2412df_0
  utfcpp             conda-forge/win-64::utfcpp-3.2.3-h57928b3_0
  vtk                pkgs/main/win-64::vtk-9.0.3-py310ha6ea5fc_203
  win32_setctime     conda-forge/noarch::win32_setctime-1.1.0-pyhd8ed1ab_0
  zstd               pkgs/main/win-64::zstd-1.5.5-hd43e919_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2023.01.10~ --> conda-forge::ca-certificates-2023.5.7-h56e8100_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main/win-64::certifi-2023.5.7-py~ --> conda-forge/noarch::certifi-2023.5.7-pyhd8ed1ab_0


Proceed ([y]/n)? y


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(scipy) PS C:\Users\fusentasticus>
(scipy) PS C:\Users\fusentasticus> conda install -c conda-forge pymeshfix    
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\fusentasticus\anaconda3\envs\scipy

  added / updated specs:
    - pymeshfix


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    double-conversion-3.1.7    |       h0e60522_0         116 KB  conda-forge
    ffmpeg-4.3.1               |       ha925a31_0        26.2 MB  conda-forge
    glew-2.1.0                 |       h39d44d4_2         941 KB  conda-forge
    icu-69.1                   |       h0e60522_0        16.4 MB  conda-forge
    libblas-3.9.0              |            8_mkl         3.9 MB  conda-forge
    libcblas-3.9.0             |            8_mkl         3.9 MB  conda-forge
    libclang-13.0.1            |default_h66ee7f4_1        19.3 MB  conda-forge
    liblapack-3.9.0            |            8_mkl         3.9 MB  conda-forge
    libtiff-4.4.0              |       h8a3f274_2         837 KB
    libzlib-1.2.13             |       hcfcfb64_4          70 KB  conda-forge
    lz4-c-1.9.3                |       h8ffe710_1         135 KB  conda-forge
    m2w64-gcc-libgfortran-5.3.0|                6         342 KB  conda-forge
    m2w64-gcc-libs-5.3.0       |                7         520 KB  conda-forge
    m2w64-gcc-libs-core-5.3.0  |                7         214 KB  conda-forge
    m2w64-gmp-6.1.0            |                2         726 KB  conda-forge
    m2w64-libwinpthread-git-5.0.0.4634.697f757|                2          31 KB  conda-forge
    mkl-2020.4                 |     hb70f87d_311       172.4 MB  conda-forge
    msys2-conda-epoch-20160418 |                1           3 KB  conda-forge
    numpy-1.24.3               |  py310hd02465a_0         5.7 MB  conda-forge
    openssl-1.1.1t             |       hcfcfb64_0         5.0 MB  conda-forge
    proj-8.2.0                 |       h1cfcee9_0         2.7 MB  conda-forge
    pugixml-1.11.4             |       h0e60522_0         211 KB  conda-forge
    pymeshfix-0.16.1           |  py310h71350ef_1         1.4 MB  conda-forge
    qt-5.12.9                  |       h556501e_6       106.1 MB  conda-forge
    scipy-1.10.1               |  py310h578b7cb_3        17.2 MB  conda-forge
    tbb-2020.2                 |       h2d74725_4         175 KB  conda-forge
    tbb-devel-2020.2           |       h2d74725_4         2.3 MB  conda-forge
    ucrt-10.0.22621.0          |       h57928b3_0         1.2 MB  conda-forge
    vc14_runtime-14.34.31931   |      h5081d32_16         709 KB  conda-forge
    vs2015_runtime-14.34.31931 |      hed1258a_16          16 KB  conda-forge
    vtk-9.1.0                  |no_osmesa_py310h4ada9a1_100        33.5 MB  conda-forge
    zlib-1.2.13                |       hcfcfb64_4         113 KB  conda-forge
    zstd-1.5.2                 |       h12be248_6         282 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       426.5 MB

The following NEW packages will be INSTALLED:

  libblas            conda-forge/win-64::libblas-3.9.0-8_mkl
  libcblas           conda-forge/win-64::libcblas-3.9.0-8_mkl
  liblapack          conda-forge/win-64::liblapack-3.9.0-8_mkl
  libzlib            conda-forge/win-64::libzlib-1.2.13-hcfcfb64_4
  m2w64-gcc-libgfor~ conda-forge/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     conda-forge/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ conda-forge/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ conda-forge/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  msys2-conda-epoch  conda-forge/win-64::msys2-conda-epoch-20160418-1
  pugixml            conda-forge/win-64::pugixml-1.11.4-h0e60522_0
  pymeshfix          conda-forge/win-64::pymeshfix-0.16.1-py310h71350ef_1
  tbb-devel          conda-forge/win-64::tbb-devel-2020.2-h2d74725_4
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_0
  vc14_runtime       conda-forge/win-64::vc14_runtime-14.34.31931-h5081d32_16

The following packages will be REMOVED:

  mkl-service-2.4.0-py310h2bbff1b_1
  mkl_fft-1.3.6-py310h4ed8f06_1
  mkl_random-1.2.2-py310h4ed8f06_1
  numpy-base-1.24.3-py310h65a83cf_1
  qt-main-5.15.2-he8e5bd7_7
  qt-webengine-5.15.9-hb9a9bb5_5

The following packages will be UPDATED:

  ffmpeg                                   4.2.3-ha925a31_0 --> 4.3.1-ha925a31_0
  icu                        pkgs/main::icu-58.2-ha925a31_3 --> conda-forge::icu-69.1-h0e60522_0
  libclang           pkgs/main::libclang-12.0.0-default_h6~ --> conda-forge::libclang-13.0.1-default_h66ee7f4_1
  proj                     pkgs/main::proj-6.2.1-h3758d61_0 --> conda-forge::proj-8.2.0-h1cfcee9_0
  scipy              pkgs/main::scipy-1.10.1-py310h309d312~ --> conda-forge::scipy-1.10.1-py310h578b7cb_3
  vs2015_runtime     pkgs/main::vs2015_runtime-14.27.29016~ --> conda-forge::vs2015_runtime-14.34.31931-hed1258a_16        
  vtk                pkgs/main::vtk-9.0.3-py310ha6ea5fc_203 --> conda-forge::vtk-9.1.0-no_osmesa_py310h4ada9a1_100
  zlib                    pkgs/main::zlib-1.2.13-h8cc25b3_0 --> conda-forge::zlib-1.2.13-hcfcfb64_4

The following packages will be SUPERSEDED by a higher-priority channel:

  glew                     pkgs/main::glew-2.2.0-hd77b12b_0 --> conda-forge::glew-2.1.0-h39d44d4_2
  lz4-c                   pkgs/main::lz4-c-1.9.4-h2bbff1b_0 --> conda-forge::lz4-c-1.9.3-h8ffe710_1
  mkl                pkgs/main::mkl-2023.1.0-h8bd8f75_46356 --> conda-forge::mkl-2020.4-hb70f87d_311
  numpy              pkgs/main::numpy-1.24.3-py310h055cbcc~ --> conda-forge::numpy-1.24.3-py310hd02465a_0
  openssl              pkgs/main::openssl-1.1.1t-h2bbff1b_0 --> conda-forge::openssl-1.1.1t-hcfcfb64_0
  qt                        pkgs/main::qt-5.15.7-haa95532_0 --> conda-forge::qt-5.12.9-h556501e_6
  tbb                    pkgs/main::tbb-2021.8.0-h59b6b97_0 --> conda-forge::tbb-2020.2-h2d74725_4
  zstd                     pkgs/main::zstd-1.5.5-hd43e919_0 --> conda-forge::zstd-1.5.2-h12be248_6

The following packages will be DOWNGRADED:

  double-conversion                        3.2.0-h0e60522_0 --> 3.1.7-h0e60522_0
  libtiff                                  4.5.0-h6c2663c_2 --> 4.4.0-h8a3f274_2


Proceed ([y]/n)? y


Downloading and Extracting Packages
zstd-1.5.2           | 282 KB    | ############################################################################### | 100%      
icu-69.1             | 16.4 MB   | ############################################################################### | 100%      
scipy-1.10.1         | 17.2 MB   | ############################################################################### | 100%      
libblas-3.9.0        | 3.9 MB    | ############################################################################### | 100%      
vs2015_runtime-14.34 | 16 KB     | ############################################################################### | 100%      
vtk-9.1.0            | 33.5 MB   | ############################################################################### | 100%      
glew-2.1.0           | 941 KB    | ############################################################################### | 100%      
lz4-c-1.9.3          | 135 KB    | ############################################################################### | 100%      
libclang-13.0.1      | 19.3 MB   | ############################################################################### | 100%      
zlib-1.2.13          | 113 KB    | ############################################################################### | 100%      
                                                                                                                          
Preparing transaction: done                                                                                               
Verifying transaction: done                                                                                               
Executing transaction: done  
```</div>

**Comment by adeak** [comment]
Just a quick comment: I've seen the same error before, and it was about a version incompatibility between pillow and some underlying image library, maybe `libpng` or `libtiff`. In my case I was on an old Python version (3.6). One of the dependencies was pinned to an old version, but the `lib*` indirect dependency was unpinned and a too new version was installed, breaking `PIL`. You can probably just try `import PIL` and see the same error.

You'll probably have to downgrade some of the packages. It's possible that 3.10 is new enough that some dependencies are more outdated than others, leading to a relatively large version gap between dependent and dependency.

**Comment by adeak** [comment]
I misremembered. In my case the exact issue was `pillow` 5.2.0 vs `libdeflate` 1.17. Latter had to be downgraded to 1.8 to resolve the same error. The reason is probably similar, but bit different detsils.

**Comment by ccalvocm** [comment]
I don't think its a pillow's issue but matplotlib's. Original @fusentasticus  issue comes from image from matplotlib. I already solved this issue on [https://github.com/pyvista/pyvista/discussions/4426](https://github.com/pyvista/pyvista/discussions/4426)

**Comment by adeak** [comment]
@ccalvocm on the one hand that's good news. On the other hand it would be nice to know both for your setup and of @fusentasticus whether you just installed pyvista in a clean env. From the original post here it seemed to me that this was a brand new conda env and only `pyvista` and `pymeshfix` were installed in it. If this leads to a broken installation then we should know about this.

So did you do this, or did you start from an existing env?

**Comment by ccalvocm** [comment]
@adeak @fusentasticus  

From the terminal I did:

`conda create -n pyvista python=3.10.11`
`conda activate pyvista`
`conda install -c conda-forge pyvista -y`
`conda install -c conda-forge pymeshfix -y`

Everything working fine

**Comment by adeak** [comment]
Perfect, thanks a lot @ccalvocm.

@fusentasticus could you please try the same?
