### ISSUE TITLE
requirements needed for pyvista-plot sphinx directive

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#4620]
### Describe the bug, what's wrong, and what you expected.

`pyvista-plot` directive worked with `pip install pyvista` in pyvista<0.40.  In pyvista 0.40, trame package is imported which causes the build to fail.  Using `pip install pyvista[trame]` results in:

```txt
Warning, treated as error:
/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pyransame/surface.py:docstring of pyransame.surface.random_surface_points:43:Exception occurred in plotting pyransame-random_surface_points-1
 from /home/runner/work/pyransame/pyransame/doc/_stubs/pyransame.random_surface_points.rst:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pyvista/trame/jupyter.py", line 352, in elegantly_launch
    import nest_asyncio
ModuleNotFoundError: No module named 'nest_asyncio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pyvista/ext/plot_directive.py", line 325, in _run_code
    exec(code, ns)
  File "<string>", line 17, in <module>
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pyvista/plotting/plotter.py", line 6701, in show
    self.last_vtksz = self.export_vtksz(filename=None)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pyvista/plotting/plotter.py", line 569, in export_vtksz
    elegantly_launch(pyvista.global_theme.trame.jupyter_server_name)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pyvista/trame/jupyter.py", line 354, in elegantly_launch
    raise ImportError(
ImportError: Please install `nest_asyncio` to automagically launch the trame server without await. Or, to avoid `nest_asynctio` run:

    from pyvista.trame.jupyter import launch_server
    await launch_server().ready
make: *** [Makefile:20: html] Error 2
make: Leaving directory '/home/runner/work/pyransame/pyransame/doc'
Error: Process completed with exit code 2.
```

See https://github.com/MatthewFlamm/pyransame/actions/runs/5446695403/jobs/9907797229#step:7:54

### Steps to reproduce the bug.

See https://github.com/MatthewFlamm/pyransame/pull/74

### System Information

```shell
Need to update the CI, but will get.
```

**Comment by banesullivan** [comment]
I'll make a patch for this asap
