### ISSUE TITLE
Plotting cell with non-planar face throws exception

### ISSUE THREAD

**Issue by dionhaefner** [pyvista/pyvista#4707]
### Describe the bug, what's wrong, and what you expected.

Trying to plot a cell with a non-planar face throws a `ValueError`:

```
>>> get_cell(cellid).plot()
Traceback (most recent call last):
  File "/Users/dion/codes/sandbox-dion/blocky/test_real.py", line 13, in <module>
    mesh.get_cell(cell).plot()
  File "/Users/dion/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py", line 142, in plot
    self.cast_to_unstructured_grid().plot(**kwargs)
  File "/Users/dion/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/cell.py", line 177, in cast_to_unstructured_grid
    return pyvista.UnstructuredGrid(*args)
  File "/Users/dion/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/pointset.py", line 1312, in __init__
    self._check_for_consistency()
  File "/Users/dion/.virtualenvs/science/lib/python3.10/site-packages/pyvista/core/pointset.py", line 1464, in _check_for_consistency
    raise ValueError(
ValueError: Number of cell types (1) must match the number of cells 0)
```

### Steps to reproduce the bug.

```python
cell_type = CellType.POLYHEDRON
cell_points = [[ 1.03791904  0.30976132 -0.34050989]
 [ 1.03685999  0.30017006 -0.32543549]
 [ 1.03750801  0.3124826  -0.32517678]
 [ 1.02476108  0.29915988 -0.32668063]
 [ 1.02512503  0.31213984 -0.32542327]
 [ 1.02444935  0.30510914 -0.33619115]
 [ 1.02858233  0.30887827 -0.34128037]]
cell_point_ids = [0, 1, 2, 3, 4, 5, 6]
face_point_ids = [[3, 1, 2, 4], [6, 0, 1, 3, 5], [3, 4, 6, 5], [2, 1, 0], [6, 4, 2, 0]]

# construct cell from the above, couldn't figure out how to do this with the public API ...
# cell = Cell(...)

cell.plot()
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Wed Jul 26 12:23:41 2023 CEST

                OS : Darwin
            CPU(s) : 10
           Machine : arm64
      Architecture : 64bit
               RAM : 16.0 GiB
       Environment : Python
       File system : apfs
        GPU Vendor : Apple
      GPU Renderer : Apple M1 Pro
       GPU Version : 4.1 Metal - 83.1

  Python 3.10.12 (main, Jun  7 2023, 00:38:32) [Clang 14.0.3
  (clang-1403.0.22.14.1)]

           pyvista : 0.38.5
               vtk : 9.2.6
             numpy : 1.25.0
           imageio : 2.27.0
            scooby : 0.7.1
             pooch : v1.7.0
        matplotlib : 3.7.1
           IPython : 8.8.0
           cmocean : 2.0
        ipywidgets : 7.7.0
             scipy : 1.10.1
              tqdm : 4.64.0
            meshio : 5.0.0
             trame : 2.5.0
      trame_client : 2.9.4
      trame_server : 2.11.4
         trame_vtk : 2.5.4
      nest_asyncio : 1.5.5
```

### Screenshots

Cell plotted with ParaView:

<img width="374" alt="Screenshot 2023-07-26 at 12 24 14" src="https://github.com/pyvista/pyvista/assets/11994217/e2a3a462-8809-4629-9a51-0b0be5cfa3e2">

**Comment by MatthewFlamm** [comment]
From the traceback, you made an UnstructuredGrid.  The format of the cell id array is different than what you have in your example above. https://docs.pyvista.org/version/stable/examples/00-load/create-polyhedron.html

Specifically look at Polyhedron connectivity array section compared to your code.

**Comment by dionhaefner** [comment]
The real code in question is a bit different. I did not construct the polyhedral cell by hand, it comes from a valid VTK file containing an unstructured mesh:

```python
mesh = pv.read("data.vtu")
mesh.get_cell(bad_cell_id).plot()  # kaboom
```

Since the VTK file itself is valid it was my interpretation that this is a bug in pyvista.

**Comment by dionhaefner** [comment]
Okay I think I got it. Full reproducer:

```python
import pyvista as pv

points = (
[[ 1.03791904,  0.30976132, -0.34050989],
 [ 1.03685999,  0.30017006, -0.32543549],
 [ 1.03750801,  0.3124826, -0.32517678],
 [ 1.02476108,  0.29915988, -0.32668063],
 [ 1.02512503,  0.31213984, -0.32542327],
 [ 1.02444935,  0.30510914, -0.33619115],
 [ 1.02858233,  0.30887827, -0.34128037]]
)

cell_point_ids = [7, 0, 1, 2, 3, 4, 5, 6]

polyhedron_connectivity = [
    # NItems will go here
    5,  # number of faces
    4,  # number of points in face0
    3, 1, 2, 4,
    5,  # number of points in face1
    6, 0, 1, 3, 5,
    4,
    3, 4, 6, 5,
    3,
    2, 1, 0,
    4,
    6, 4, 2, 0
]
polyhedron_connectivity = [len(polyhedron_connectivity)] + polyhedron_connectivity

cell_type = pv.CellType.POLYHEDRON

grid = pv.UnstructuredGrid(polyhedron_connectivity, [cell_type], points)

grid.get_cell(0).plot()
```

**Comment by MatthewFlamm** [comment]
I'm glad my misread led to reproducible code.  Thank you, this helps pinpoint the issue.  I believe this is a bug in casting to instructed grid for polyhedron cells, not in the plotting itself.

Specifically these lines do not follow the PyVista API for creating a Polyhedron cell:

https://github.com/pyvista/pyvista/blob/d09de76fef6a1164eda2f63dfdfb2fd6a75c308a/pyvista/core/cell.py#L179-L183

**Comment by dionhaefner** [comment]
Oh, so the fact that this is non-planar wasn't even relevant. That's funny.

Thanks for the PRs :)

**Comment by MatthewFlamm** [comment]
Not relevant, but non-planar faces are not well supported anyway.  You might find artifacts in plotting and problems in data processing.
