### ISSUE TITLE
`ImageData().points` raises unexpected ValueError

### ISSUE THREAD

**Issue by user27182** [pyvista/pyvista#4711]
### Describe the bug, what's wrong, and what you expected.

`ImageData().points` raises an unexpected `ValueError`. I would have expected that an empty array be returned, which is the behaviour with `PolyData().points` and `UnstructuredGrid().points`

### Steps to reproduce the bug.

Running:
```python
import pyvista
pyvista.ImageData().points
```
Will produce:
```
Traceback (most recent call last):
  File "\pyvista\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-c3545438d535>", line 1, in <module>
    im.points
  File "c\pyvista\pyvista\core\grid.py", line 629, in points
    x = np.insert(np.cumsum(np.full(nx, dx)), 0, 0.0) + ox
  File "\pyvista\lib\site-packages\numpy\core\numeric.py", line 329, in full
    a = empty(shape, dtype, order)
ValueError: negative dimensions are not allowed
```

Compare this to:
```python
import pyvista
pyvista.PolyData().points  # pyvista_ndarray([], shape=(0, 3), dtype=float64)
pyvista.UnstructuredGrid().points  # pyvista_ndarray([], shape=(0, 3), dtype=float64)
```

### System Information

```shell
OS : Windows
            CPU(s) : 12
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.8 GiB
       Environment : IPython
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics 630
       GPU Version : 4.5.0 - Build 30.0.100.9864
  MathText Support : False
  Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64
  bit (AMD64)]
           pyvista : 0.42.dev0
               vtk : 9.2.6
             numpy : 1.25.1
        matplotlib : 3.7.2
            scooby : 0.7.2
             pooch : v1.7.0
           imageio : 2.31.1
           IPython : 8.14.0
          colorcet : 3.0.1
           cmocean : v3.0.3
        ipyvtklink : 0.2.3
        ipywidgets : 7.7.5
             scipy : 1.11.1
              tqdm : 4.65.0
            meshio : 5.3.4
        jupyterlab : 4.0.3
         pythreejs : 2.4.2
    pytest_pyvista : 0.1.8
             trame : 2.5.2
      trame_client : 2.9.4
      trame_server : 2.11.7
         trame_vtk : 2.5.8
      nest_asyncio : 1.5.6
```

**Comment by MatthewFlamm** [comment]
We can return early with an empty array if any dimension value is 0.
