### ISSUE TITLE
Plotter AttributeError: 'NoneType' object has no attribute 'add_key_event'

### ISSUE THREAD

**Issue by gsal** [pyvista/pyvista#4750]
### Describe the bug, what's wrong, and what you expected.

I think I have found a bug!

Traceback (most recent call last):
  File "/path/to/.../file.py", line 10, in <module>
    p.add_key_event("q",p.close())
  File "/path/to/.../.venv/lib64/python3.9/site-packages/pyvista/plotting/plotter.py", line 1878, in add_key_event
    self.iren.add_key_event(*args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'add_key_event'

### Steps to reproduce the bug.

```python
import pyvista as pv
from pyvista import examples

vol = examples.download_brain()
p = pv.Plotter()
p.add_key_event("q",p.close())
p.show()
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Mon Aug 07 22:25:21 2023 EDT

                  OS : Linux
              CPU(s) : 48
             Machine : x86_64
        Architecture : 64bit
                 RAM : 1511.0 GiB
         Environment : Python
         File system : xfs
          GPU Vendor : NVIDIA Corporation
        GPU Renderer : Quadro RTX 6000/PCIe/SSE2
         GPU Version : 4.5.0 NVIDIA 470.182.03
    MathText Support : False

  Python 3.9.16 (main, May 29 2023, 00:00:00)  [GCC 11.3.1 20221121 (Red Hat
  11.3.1-4)]

             pyvista : 0.41.1
                 vtk : 9.2.6
               numpy : 1.25.2
          matplotlib : 3.7.2
              scooby : 0.7.2
               pooch : v1.7.0
             imageio : 2.31.1
           pyvistaqt : 0.11.0
               PyQt5 : 5.15.9
             IPython : 8.14.0
            colorcet : 3.0.1
             cmocean : v3.0.3
          ipyvtklink : 0.2.3
          ipywidgets : 7.8.0
                tqdm : 4.65.0
              meshio : 5.3.4
          jupyterlab : 4.0.4
           pythreejs : 2.4.2
               trame : 3.1.0
        trame_client : 2.10.0
        trame_server : 2.11.7
           trame_vtk : 2.5.8
jupyter_server_proxy : 4.0.0
        nest_asyncio : 1.5.7
--------------------------------------------------------------------------------
```

**Comment by tkoyama010** [comment]
https://github.com/pyvista/pyvista/blob/bbd1d70d97cb1723df76c78e5f129d4a1b9ba6e7/pyvista/plotting/plotter.py#L4627-L4633
`close` method has an extra argument render. To properly define the callback function, you need to define a function with no arguments. To do so, we need to define the following.
```python
import pyvista

pl = pyvista.Plotter()

def close():
    pl.close()

pl.add_mesh(pyvista.Sphere())
pl.add_key_event('q', close)
pl.show()
```
@gsal Could you confirm that this code will run without problems in your environment?

**Comment by gsal** [comment]
I thought I did; I had replied and marked your post as the answered.

Anyway, yes, the removal of the parenthesis in the .close call solved the issue.

**Comment by tkoyama010** [comment]
I have partially solved the problem with #4820, but I am not completely sure of the behavior when the close method is added, so I will reopen this once.
