### ISSUE TITLE
numpy_support module bug

### ISSUE THREAD

**Issue by acse-yl1922** [pyvista/pyvista#5457]
### Describe the bug, what's wrong, and what you expected.

"numpy_support.py", line 74, in get_vtk_to_numpy_typemap
    _vtk_np = {vtkConstants.VTK_BIT:numpy.bool,
  File "/path_to_env/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.

This err message raises with Name: numpy Version: 1.26.3, which indicates that some functionalities of numpy_support.py may not support newest numpy.

### Steps to reproduce the bug.

```python
test_output(model, device, output_loader, osj(path,'raw'), 'temperature', output_dir+'/meshes', mesh_name='train_e{:d}'.format(epoch), output_normalizer=output_normalizer)

def test_output(model, device, output_loader, raw_mesh_path, tag, save_mesh_path, mesh_name='mesh',output_normalizer=None):
    for i,batch in enumerate(tqdm(output_loader)):
            #some code above......
            mesh.point_data[tag+'_label'] = label_denorm.detach().cpu() #bug occurs here
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Thu Jan 11 15:21:18 2024 EST

                OS : Linux
            CPU(s) : 64
           Machine : x86_64
      Architecture : 64bit
               RAM : 251.5 GiB
       Environment : Jupyter
       File system : ext4
       GPU Details : error
  MathText Support : False

  Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]

           pyvista : 0.43.1
               vtk : 9.0.3
             numpy : 1.26.3
        matplotlib : 3.8.0
            scooby : 0.9.2
             pooch : 1.7.0
            pillow : 10.0.1
             PyQt5 : 5.15.10
           IPython : 8.15.0
             scipy : 1.11.4
              tqdm : 4.65.0
      nest_asyncio : 1.5.6

  Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303
  for Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

### Screenshots

fully err info:
Traceback (most recent call last):
  File "/home/yongqi/poisson/sandbox/fit_batch_gcn_plus_multiscale.py", line 168, in <module>
    test_output(model, device, output_loader, osj(path,'raw'), 'temperature', output_dir+'/meshes', mesh_name='train_e{:d}'.format(epoch), output_normalizer=output_normalizer)
  File "/home/yongqi/poisson/sandbox/utilities/train.py", line 67, in test_output
    mesh.point_data[tag+'_prediction'] = output_denorm.detach().cpu()
  File "/home/yongqi/.conda/envs/gnnEnv/lib/python3.10/site-packages/pyvista/core/datasetattributes.py", line 227, in __setitem__
    self.set_array(value, name=key)
  File "/home/yongqi/.conda/envs/gnnEnv/lib/python3.10/site-packages/pyvista/core/datasetattributes.py", line 579, in set_array
    vtk_arr = self._prepare_array(data, name, deep_copy)
  File "/home/yongqi/.conda/envs/gnnEnv/lib/python3.10/site-packages/pyvista/core/datasetattributes.py", line 819, in _prepare_array
    return convert_array(copy, name, deep=deep_copy)
  File "/home/yongqi/.conda/envs/gnnEnv/lib/python3.10/site-packages/pyvista/core/utilities/arrays.py", line 218, in convert_array
    vtk_data = _vtk.numpy_to_vtk(num_array=arr, deep=deep, array_type=array_type)
  File "/home/yongqi/.conda/envs/gnnEnv/lib/python3.10/site-packages/vtkmodules/util/numpy_support.py", line 164, in numpy_to_vtk
    arr_dtype = get_numpy_array_type(vtk_typecode)
  File "/home/yongqi/.conda/envs/gnnEnv/lib/python3.10/site-packages/vtkmodules/util/numpy_support.py", line 94, in get_numpy_array_type
    return get_vtk_to_numpy_typemap()[vtk_array_type]
  File "/home/yongqi/.conda/envs/gnnEnv/lib/python3.10/site-packages/vtkmodules/util/numpy_support.py", line 74, in get_vtk_to_numpy_typemap
    _vtk_np = {vtkConstants.VTK_BIT:numpy.bool,
  File "/home/yongqi/.conda/envs/gnnEnv/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?

**Comment by acse-yl1922** [comment]
after modifying: 'numpy_support.py, line 74' in my local conda env:
```python
_vtk_np = {vtkConstants.VTK_BIT:numpy.bool,
                    #some other code...}
```
to:
```python
_vtk_np = {vtkConstants.VTK_BIT:numpy.bool_,
                    #some other code...}
```
problem successfully resolved. Maybe this modification can be considered to add on official docs?

**Comment by MatthewFlamm** [comment]
This error happens inside `vtkmodules` which is also known as `vtk`.  This error should only happen for vtk version 9.0.3 and a newer version of numpy.  You can either downgrade numpy or upgrade vtk.  Our CI limits numpy to <1.24 for this version of vtk.
