### ISSUE TITLE
Documentation fails for volume.py

### ISSUE THREAD

**Issue by GuillaumeFavelier** [pyvista/pyvista#578]
There is an issue on `master` with the documentation of `volume.py`. I tracked it down to `download_damavand_volcano`:

https://travis-ci.org/pyvista/pyvista/jobs/645456896#L1448-L1465

<details><summary>more details</summary>
<p>
Unexpected failing examples:

/home/travis/build/pyvista/pyvista/examples/02-plot/volume.py failed leaving traceback:

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage

    out = func()

  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__

    exec(self.code, self.globals)

  File "/home/travis/build/pyvista/pyvista/examples/02-plot/volume.py", line 113, in <module>

    large_vol = examples.download_damavand_volcano()

  File "/home/travis/build/pyvista/pyvista/pyvista/examples/downloads.py", line 589, in download_damavand_volcano

    volume = _download_and_read("damavand-volcano.vtk")

  File "/home/travis/build/pyvista/pyvista/pyvista/examples/downloads.py", line 62, in _download_and_read

    return pyvista.read(saved_file, file_format=file_format)

  File "/home/travis/build/pyvista/pyvista/pyvista/utilities/fileio.py", line 203, in read

    return read_legacy(filename)

  File "/home/travis/build/pyvista/pyvista/pyvista/utilities/fileio.py", line 140, in read_legacy

    raise AssertionError('No output when using VTKs legacy reader')

AssertionError: No output when using VTKs legacy reader
</p>

**Comment by banesullivan** [comment]
@GuillaumeFavelier, we ran out of bandwidth for git LFS and an example dataset in volume.py is the culpri. You’re getting the error because GitHub isn’t letting us access that file until next month. We need to move that file elsewhere or remove that particular example. 

It’s the volcano example volume 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
I’ll see if I can compress the file down to not use git LFS

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GuillaumeFavelier** [comment]
Thank you @banesullivan for the fast reply!

**Comment by banesullivan** [comment]
@GuillaumeFavelier, all should be good now. We are no longer using git LFS for that file

**Comment by GuillaumeFavelier** [comment]
Thank you! I restarted the CIs and everything is fine now. Closing.
