### ISSUE TITLE
A bug with the jupyter 

### ISSUE THREAD

**Issue by Tomcat4891** [pyvista/pyvista#5906]
### Describe the bug, what's wrong, and what you expected.

I found a bug!

After updating pyvista (conda update --all) the following error appeared on all systems

### Steps to reproduce the bug.

```python
import numpy as np
import pyvista as pv
print(pv.Report())

values = np.linspace(0, 10, 1000).reshape((20, 5, 10))
values.shape

# Create the spatial reference
grid = pv.ImageData()

# Set the grid dimensions: shape + 1 because we want to inject our values on
#   the CELL data
grid.dimensions = np.array(values.shape) + 1

# Edit the spatial reference
grid.origin = (100, 33, 55.6)  # The bottom left corner of the data set
grid.spacing = (1, 5, 2)  # These are the cell sizes along each axis

# Add the data values to the cell data
grid.cell_data["values"] = values.flatten(order="F")  # Flatten the array

# Now plot the grid
grid.plot(show_edges=True)


```

### System Information

```shell
Date: Thu Apr 11 21:44:48 2024 +07

                OS : Linux
            CPU(s) : 12
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.1 GiB
       Environment : Jupyter
       File system : ext4
        GPU Vendor : Mesa
      GPU Renderer : llvmpipe (LLVM 15.0.7, 256 bits)
       GPU Version : 4.5 (Core Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
  MathText Support : True

  Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC
  12.3.0]

           pyvista : 0.43.5
               vtk : 9.2.6
             numpy : 1.26.4
        matplotlib : 3.8.4
            scooby : 0.9.2
             pooch : 1.8.1
...
         trame_vtk : 2.8.5
     trame_vuetify : 2.4.3
      nest_asyncio : 1.6.0
```

### Screenshots

```shell
Error handling request
Traceback (most recent call last):
  File "/home/andrew/intelpython3/envs/py312/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrew/intelpython3/envs/py312/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrew/intelpython3/envs/py312/lib/python3.12/site-packages/wslink/backends/aiohttp/__init__.py", line 215, in handleWsRequest
    await self.onMessage(is_binary(msg), msg, client_id)
  File "/home/andrew/intelpython3/envs/py312/lib/python3.12/site-packages/wslink/protocol.py", line 254, in onMessage
    payload = payload.decode("utf-8")
              ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 0: invalid start byte
```

**Comment by Tomcat4891** [comment]
The problem is solved.

The problem is solved. It is necessary to update anaconda packages again.  I.e. consistently call conda update --all twice.
