### ISSUE TITLE
Cannot serialize MultiBlock (dataset of type 13) with pickle

### ISSUE THREAD

**Issue by kalingibbons** [pyvista/pyvista#6419]
### Describe the bug, what's wrong, and what you expected.

Attempting to serialize a pyvista.MultiBlock results in a TypeError being thrown.

I expected the serialization to proceed.

Perhaps a loop needs to be added to `pyvista.core.DataObject.__getstate__`?

### Steps to reproduce the bug.

```python
import pickle
import pyvista as pv

multi_block = pv.MultiBlock((pv.Cube(), pv.Sphere()))
with open('failed.pkl', 'wb') as f:
    pickle.dump(multi_block, f)
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\kalin\Documents\git-projects\knee-mesher\.env\Lib\site-packages\pyvista\core\dataobject.py", line 728, in __getstate__
    raise TypeError(f'Cannot pickle dataset of type {self.GetDataObjectType()}')
TypeError: Cannot pickle dataset of type 13
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Fri Jul 26 13:30:03 2024 Mountain Daylight Time

                OS : Windows (10 10.0.19045 SP0 Multiprocessor Free)
            CPU(s) : 12
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.9 GiB
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 560.70
  MathText Support : False

  Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:27:10) [MSC
  v.1938 64 bit (AMD64)]

           pyvista : 0.44.1
               vtk : 9.3.1
             numpy : 1.26.4
        matplotlib : 3.9.1
            scooby : 0.10.0
             pooch : 1.8.2
            pillow : 10.4.0
           imageio : 2.34.2
             PyQt5 : 5.15.9
           IPython : 8.26.0
        ipywidgets : 8.1.3
             scipy : 1.14.0
              tqdm : 4.66.4
            meshio : 5.3.5
        jupyterlab : 4.2.4
      nest_asyncio : 1.6.0
--------------------------------------------------------------------------------
```

**Comment by user27182** [comment]
For reference, object type 13 is `VTK_MULTIBLOCK_DATA_SET` defined here:
https://vtk.org/doc/nightly/html/vtkType_8h.html#a3605b6651f3217f8a574ee9d721d36c7
