### ISSUE TITLE
trame jupyter backend shows 404: Not Found

### ISSUE THREAD

**Issue by oliverlee** [pyvista/pyvista#6650]
### Describe the bug, what's wrong, and what you expected.

When trying to plot using the trame backend, I get a box with a 404 Error instead of an interactive plot. The static backend works fine. matplotlib interactive widgets also appear to work.

I am not using Conda or a standard Python package managers. I am using Bazel to set up a hermetic Python 3.12 toolchain and to pull in pip packages. A Python script starts the Jupyter notebook app and server, which is run via `bazel run //python:notebook`. This command lazily pulls in all Python dependencies.

### Steps to reproduce the bug.

I can try and create a smaller example if this one is too large. I don't have a Linux x86-64 machine at the moment and don't know if the same issue exists.

* Clone repo and checkout this [PR](https://github.com/oliverlee/rigid-geometric-algebra/pull/49).
* Install `bazelisk`. I use [brew](https://formulae.brew.sh/formula/bazelisk) on both macOS and Linux.
* Within the repo, run `bazel run //python:notebook` to open the notebook in the browser and then run the appropriate cell.

### System Information

```shell
Date: Sat Sep 14 01:42:17 2024 PDT

                  OS : Darwin (macOS 14.6.1)
              CPU(s) : 8
             Machine : arm64
        Architecture : 64bit
                 RAM : 8.0 GiB
         Environment : Jupyter
         File system : apfs
          GPU Vendor : Apple
        GPU Renderer : Apple M1
         GPU Version : 4.1 Metal - 88.1
    MathText Support : True

  Python 3.12.4 (main, Jul 25 2024, 22:11:22) [Clang 18.1.8 ]

             pyvista : 0.44.1
                 vtk : 9.3.1
               numpy : 2.1.1
          matplotlib : 3.9.2
              scooby : 0.10.0
               pooch : 1.8.2
              pillow : 10.4.0
             imageio : 2.35.1
             IPython : 8.27.0
            colorcet : 3.1.0
             cmocean : 4.0.3
          ipywidgets : 8.1.5
              meshio : 5.3.5
          jupyterlab : 4.2.5
               trame : 3.6.5
        trame_client : 3.2.5
        trame_server : 3.1.2
           trame_vtk : 2.8.10
       trame_vuetify : 2.7.1
jupyter_server_proxy : 4.4.0
        nest_asyncio : 1.6.0
```

### Screenshots

<img width="742" alt="Screenshot 2024-09-14 at 12 31 15" src="https://github.com/user-attachments/assets/43d5e776-1509-4942-b22b-5d250684c328">
<img width="740" alt="Screenshot 2024-09-14 at 12 31 32" src="https://github.com/user-attachments/assets/9fea7942-605b-4210-b57c-a2e3e6b6d187">
<img width="741" alt="Screenshot 2024-09-14 at 12 34 12" src="https://github.com/user-attachments/assets/ef369a0b-1b11-4725-b91b-01945f13d0e3">

**Comment by banesullivan** [comment]
The trame backend in PyVista requires accessing a port on localhost. We typically encourage jupyter-server-proxy or trame-jupyter-extension for this. See https://docs.pyvista.org/user-guide/jupyter/trame.html#remote-jupyter-host

**Comment by oliverlee** [comment]
Thanks, I wasn't able to see any thing with either versions of `trame_jupyter_extension` but I'm able to display something after setting up `jupyter_server_proxy`.

I enable this extension when launching the notebook app with:
```py
...
os.environ["PYVISTA_TRAME_SERVER_PROXY_PREFIX"] = "/proxy/"
...
NotebookApp.launch_instance(
    file_to_run=(workspace + "/python/Untitled.ipynb"),
    log_level=logging.DEBUG,
    # token = "",
    # password = "",
    nbserver_extensions={
        "jupyter_server_proxy": True,
    },
)
```

If I don't disable token authentication, I see this:
<img width="725" alt="Screenshot 2024-09-17 at 14 56 17" src="https://github.com/user-attachments/assets/0bf1680d-9fc4-4436-99ac-6d0126eba50c">

The token displayed in the terminal isn't accepted.

Running with token authentication shows:
<img width="673" alt="Screenshot 2024-09-17 at 14 58 37" src="https://github.com/user-attachments/assets/8526a1db-c769-4fe4-a391-5d28fca996f6">

and the corresponding console log:
<details>

```
[I 14:58:27.538 NotebookApp] 302 GET /login?next=%2Fproxy%2F52485%2Findex.html%3Fui%3DP_0x11b2207d0_0%26reconnect%3Dauto (127.0.0.1) 0.220000ms
[I 14:58:27.540 NotebookApp] 302 GET /proxy/52485/index.html?ui=P_0x11b2207d0_0&reconnect=auto (127.0.0.1) 0.350000ms
[E 14:58:27.540 NotebookApp] Uncaught exception GET /proxy/52485/index.html?ui=P_0x11b2207d0_0&reconnect=auto (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/proxy/52485/index.html?ui=P_0x11b2207d0_0&reconnect=auto', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/private/var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/bin/python/notebook.runfiles/pypi_tornado/site-packages/tornado/web.py", line 1769, in _execute
        result = await result  # type: ignore
                 ^^^^^^^^^^^^
      File "/private/var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/bin/python/notebook.runfiles/pypi_jupyter_server_proxy/site-packages/jupyter_server_proxy/handlers.py", line 167, in prepare
        web.authenticated(lambda request_handler: None)(self)
      File "/private/var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/bin/python/notebook.runfiles/pypi_tornado/site-packages/tornado/web.py", line 3298, in wrapper
        self.redirect(url)
      File "/private/var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/bin/python/notebook.runfiles/pypi_jupyter_server_proxy/site-packages/jupyter_server_proxy/websocket.py", line 83, in undisallow
        getattr(nextparent, method)(self, *args2, **kwargs2)
      File "/private/var/tmp/_bazel_oliver/e888b1acfe919fa909be3f7123974edb/execroot/rigid_geometric_algebra/bazel-out/darwin_arm64-fastbuild/bin/python/notebook.runfiles/pypi_tornado/site-packages/tornado/web.py", line 888, in redirect
        raise Exception("Cannot redirect after headers have been written")
    Exception: Cannot redirect after headers have been written
```

</details>
I do allow cookies and I don't seem to find any obvious solutions when searching the Github issues of tornado or jupyter-server-proxy.


Here's the updated package list:
<details>

```
 Python 3.12.4 (main, Jul 25 2024, 22:11:22) [Clang 18.1.8 ]

             pyvista : 0.44.1
                 vtk : 9.3.1
               numpy : 2.1.1
          matplotlib : 3.9.2
              scooby : 0.10.0
               pooch : 1.8.2
              pillow : 10.4.0
             imageio : 2.35.1
             IPython : 8.27.0
            colorcet : 3.1.0
             cmocean : 4.0.3
          ipywidgets : 8.1.5
              meshio : 5.3.5
          jupyterlab : 4.2.5
               trame : 3.6.5
        trame_client : 3.2.5
        trame_server : 3.1.2
           trame_vtk : 2.8.10
       trame_vuetify : 2.7.1
jupyter_server_proxy : 4.4.0
        nest_asyncio : 1.6.0
```

</details>

Is this something you've seen before? I saw https://github.com/pyvista/pyvista/issues/5296 but am unsure if port forwarding needs to be applied or how to do that -- I am not running within a Docker container, nor am I using a remote machine.

**Comment by banesullivan** [comment]
This seems like an issue specific to bazel and using jupyter-server-proxy with it... I'm not familar with bazel... wish I could help more. It may be worth seeing if trame-jupyter-extension (alternative to jupyter-server-proxy) works here (see docs link above)
