### ISSUE TITLE
.smooth() causes a crash

### ISSUE THREAD

**Issue by Lunascaped** [pyvista/pyvista#6996]
### Describe the bug, what's wrong, and what you expected.

When using the smooth method, pyvista complains about _textures not being an attribute of PolyData in /core/dataset.py.

I'm very confused as to how this started happening as I use this in a docker container and nothing has changed or updated that I can tell. 

```Traceback (most recent call last):
  File "/home/luna/Neptune/test.py", line 3, in <module>
    examples.download_cow().smooth()
  File "/home/luna/.local/lib/python3.11/site-packages/pyvista/core/filters/poly_data.py", line 871, in smooth
    mesh = _get_output(alg)
           ^^^^^^^^^^^^^^^^
  File "/home/luna/.local/lib/python3.11/site-packages/pyvista/core/filters/__init__.py", line 48, in _get_output
    data.copy_meta_from(ido, deep=True)
  File "/home/luna/.local/lib/python3.11/site-packages/pyvista/core/dataset.py", line 1408, in copy_meta_from
    self.clear_textures()
  File "/home/luna/.local/lib/python3.11/site-packages/pyvista/core/dataset.py", line 534, in clear_textures
    self._textures.clear()
    ^^^^^^^^^^^^^^
  File "/home/luna/.local/lib/python3.11/site-packages/pyvista/core/dataset.py", line 131, in __getattr__
    return super().__getattribute__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PolyData' object has no attribute '_textures'. Did you mean: 'textures'? ```

### Steps to reproduce the bug.

```python
import pyvista as pv
from pyvista import examples
examples.download_cow().smooth()
```

### System Information

```shell
neptune_1  |   Date: Tue Dec 17 12:02:02 2024 UTC
neptune_1  | 
neptune_1  |                 OS : Linux (Debian GNU/Linux 12)
neptune_1  |             CPU(s) : 4
neptune_1  |            Machine : x86_64
neptune_1  |       Architecture : 64bit
neptune_1  |                RAM : 15.5 GiB
neptune_1  |        Environment : Python
neptune_1  |        GPU Details : error
neptune_1  |   MathText Support : False
neptune_1  | 
neptune_1  |   Python 3.11.11 (main, Dec  4 2024, 20:38:25) [GCC 12.2.0]
neptune_1  | 
neptune_1  |            pyvista : 0.40.0
neptune_1  |                vtk : 9.4.0
neptune_1  |              numpy : 1.26.4
neptune_1  |         matplotlib : 3.10.0
neptune_1  |             scooby : 0.10.0
neptune_1  |              pooch : 1.8.2
neptune_1  |            imageio : 2.31.6
neptune_1  |              scipy : 1.11.4
neptune_1  | --------------------------------------------------------------------------------

(This was done inside the docker container)
```

**Comment by user27182** [comment]
Vtk 9.4 was recently released but is not yet supported.

**Comment by user27182** [comment]
Fixed with the release of PyVista 0.45 which supports vtk 9.4.2
