### ISSUE TITLE
rotate_* should not be accessible for implicitly defined meshes

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#811]
`RectilinearGrid` and `UniformGrid` should not have the `rotate_*` methods as the points of those meshes cannot be directly set and those mesh types cannot be on any rotated reference frame.

Currently, the following code throws no error and really does nothing:

```py
from pyvista import examples
m = examples.load_uniform()
m.rotate_z(90)
```

**Comment by whophil** [comment]
We now use `vtkTransform` to do all transformations (see https://github.com/pyvista/pyvista/pull/1166). This method will automatically cast a `vtkRectilinearGrid` to a `vtkStructuredGrid` upon transformation. But because the `rotate_*` methods are in-place, this now throws a somewhat hard-to-understand error about type incompatibility. At least it's an error!

```python
from pyvista import examples
m = examples.load_rectilinear()
m.rotate_z(90)
```
Raises
```
Traceback (most recent call last):
  File "/Users/phil/Library/Application Support/JetBrains/PyCharmCE2021.1/scratches/scratch_2.py", line 3, in <module>
    m.rotate_z(90)
  File "/Users/phil/Repos/pyvista/pyvista/core/dataset.py", line 503, in rotate_z
    self.transform(t, transform_all_input_vectors=transform_all_input_vectors, inplace=True)
  File "/Users/phil/Repos/pyvista/pyvista/core/filters.py", line 3097, in transform
    raise ValueError('Unable to perform in-place transformation. '
ValueError: Unable to perform in-place transformation. Input was `vtkRectilinearGrid` but output is `vtkStructuredGrid`.```

**Comment by user27182** [comment]
Support for `ImageData` rotations was added in #6616 
A warning is now issued when trying to rotate `RectilinearGrid` in #7697, though a very limited number of rotations are actually supported if the rotation matrix is a diagonal matrix
